'use client';
import {useEffect,useState} from 'react';
type Entry={id:string;status:'pending'|'contacted'|'approved'|'closed';created_at:string;data:string};
export default function Connections(){
 const [rows,setRows]=useState<Entry[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[replies,setReplies]=useState<Record<string,string>>({});
 async function load(){try{const r=await fetch('/api/connect',{cache:'no-store'}),b=await r.json() as {error?:string;requests?:Entry[]};if(!r.ok)throw Error(b.error||'Не удалось загрузить заявки');setRows(b.requests||[]);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function update(id:string,status:Entry['status']){setSaving(id);try{const r=await fetch('/api/connect',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})}),b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error||'Не удалось обновить заявку');await load();}catch(e){setError((e as Error).message);}finally{setSaving('');}}
 async function reply(id:string){const text=replies[id]?.trim();if(!text)return;setSaving(id);try{const r=await fetch('/api/connect',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,reply:text})}),b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error||'Не удалось отправить ответ');setReplies(current=>({...current,[id]:''}));await load();}catch(e){setError((e as Error).message);}finally{setSaving('');}}
 async function approveCatalog(id:string){if(!confirm('Проверили заявителя и разрешаете собрать товары только в закрытый черновик? Публикации не будет.'))return;setSaving(id);try{const r=await fetch('/api/connect',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'approveCatalog'})}),b=await r.json() as {error?:string;count?:number};if(!r.ok)throw Error(b.error||'Не удалось собрать каталог');await load();}catch(e){setError((e as Error).message);}finally{setSaving('');}}
 return <main style={{maxWidth:1000,margin:'32px auto',padding:20}}><a href="/">НайдиGo</a><h1>Заявки магазинов</h1><p>Заявка не предоставляет доступ и не публикует магазин. После проверки можно собрать каталог только в закрытый черновик.</p>{loading&&<p role="status">Загружаем…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!rows.length&&<p>Заявок пока нет.</p>}{rows.map(row=>{let b:{name?:string;city?:string;category?:string;catalogUrl?:string;catalogConsent?:boolean;catalogImport?:{count:number;at:string};draftStoreId?:string;contact?:string;note?:string;preferredChannel?:'telegram'|'max'|'phone'|'email';buyerId?:string|null;registeredProvider?:string|null;replies?:{text:string;at:string}[]};try{b=JSON.parse(row.data);}catch{return null;}const botReply=!!b.buyerId&&['telegram','max'].includes(b.registeredProvider||'');const channel={telegram:'Telegram',max:'MAX',phone:'Телефон',email:'Email'}[b.preferredChannel||'phone'];return <article key={row.id} style={{padding:20,marginTop:16,border:'1px solid #dce3ed',borderRadius:16,overflowWrap:'anywhere'}}><h2>{b.name}</h2><p>{b.city} · {b.category||'Категория не указана'} · {channel}: {b.contact}</p>{b.catalogUrl&&<p>Каталог: <a href={b.catalogUrl} target="_blank" rel="noreferrer">{b.catalogUrl}</a>{b.catalogConsent?' · разрешён заявителем':' · без разрешения на автосбор'}</p>}<p>{b.note}</p><small>{new Date(row.created_at).toLocaleString('ru-RU')}{b.registeredProvider?` · Вход через ${b.registeredProvider}`:' · Без входа'}</small>{b.catalogImport&&<p><b>Собрано в закрытый черновик: {b.catalogImport.count}</b> · <a href="/onboarding">проверить карточки</a></p>}{b.replies?.map(item=><blockquote key={item.at}>{item.text}<small> · {new Date(item.at).toLocaleString('ru-RU')}</small></blockquote>)}{botReply&&<form onSubmit={e=>{e.preventDefault();void reply(row.id)}} style={{display:'flex',gap:8,marginTop:12}}><input aria-label={'Ответ '+b.name} value={replies[row.id]||''} onChange={e=>setReplies(current=>({...current,[row.id]:e.target.value}))} maxLength={2000} required placeholder={'Ответить через '+b.registeredProvider} style={{flex:1,padding:10}}/><button disabled={saving===row.id}>Отправить</button></form>}{b.catalogUrl&&b.catalogConsent&&<button style={{marginTop:12}} disabled={saving===row.id} onClick={()=>void approveCatalog(row.id)}>{b.catalogImport?'Обновить закрытый черновик':'Разрешить автосбор в черновик'}</button>}<label style={{display:'block',marginTop:12}}>Статус заявки <select aria-label={'Статус '+b.name} disabled={saving===row.id} value={row.status} onChange={e=>void update(row.id,e.target.value as Entry['status'])}><option value="pending">Новая</option><option value="contacted">Связались</option><option value="approved">Автосбор разрешён</option><option value="closed">Закрыта</option></select></label></article>;})}</main>;
}
