import {z} from 'zod';
import {db} from '@/db';
import {actor,checkUploadOwnership,hash,privateHeaders,sameOrigin,token} from '@/lib/onboarding';
import {quota,privateResponse} from '@/lib/discovery-server';
import {notifyConnectionRequest,sendConnectionReply} from '@/lib/connection-notify';
import {buyerIdentity} from '@/lib/buyer-auth';
import {categories,type Shop} from '@/lib/model';
import {allowedSource,merchantSource,fetchApprovedMerchantSource} from '@/lib/source-fetch';
import {extractOffers} from '@/lib/offer-extraction';
import {normalize} from '@/lib/search';

type RequestData={name?:string;contactPerson?:string;phone?:string;city?:string;category?:string;catalogUrl?:string;catalogConsent?:boolean;contact?:string;preferredChannel?:string;note?:string;buyerId?:string|null;registeredProvider?:string|null;replies?:{text:string;at:string}[];draftStoreId?:string;catalogImport?:{count:number;at:string}};
type DraftRow={id:string;data:string;visibility:string;owner:string|null};
const webUrl=z.union([z.literal(''),z.string().url().max(1000).refine(value=>/^https:\/\//.test(value),'Нужна HTTPS-ссылка')]);
const storeDraft=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(2).max(200),category:z.enum(categories).default(categories[0]),city:z.string().trim().min(1).max(100),street:z.string().trim().min(1).max(300),phone:z.string().trim().min(5).max(100),site:webUrl.default(''),photos:z.array(z.string().regex(/^\/api\/photos\/[a-f0-9-]{36}$/)).max(5).default([])});
function draftGuest(req:Request){const old=req.headers.get('cookie')?.match(/(?:^|;\s*)ng_guest=([a-f0-9-]{36})/)?.[1],value=old||crypto.randomUUID();return {key:`guest:${value}`,cookie:old?null:`ng_guest=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${new URL(req.url).protocol==='https:'?'; Secure':''}`};}

async function ownedDraft(id:string,key:string){const row=await db().prepare("SELECT s.* FROM shops s JOIN onboarding o ON o.store_id=s.id WHERE s.id=? AND s.visibility='draft' AND s.owner IS NULL AND o.created_by=?").bind(id,key).first<DraftRow>();if(!row)throw new Error('Черновик магазина не найден или открыт в другом браузере');return row;}
async function previewPath(storeId:string){const raw=token(),expires=new Date(Date.now()+30*864e5).toISOString();await db().batch([db().prepare('UPDATE preview_tokens SET revoked=1 WHERE store_id=?').bind(storeId),db().prepare('INSERT INTO preview_tokens(hash,store_id,expires_at,revoked) VALUES(?,?,?,0)').bind(await hash(raw),storeId,expires)]);return `/preview/${raw}`;}

export async function GET(req:Request){
 const id=new URL(req.url).searchParams.get('draft');
 if(id){try{const who=draftGuest(req),row=await ownedDraft(z.string().uuid().parse(id),who.key),products=await db().prepare('SELECT data FROM products WHERE store_id=? ORDER BY rowid DESC').bind(id).all<{data:string}>();return privateResponse({shop:{...JSON.parse(row.data),visibility:row.visibility},products:products.results.map(item=>JSON.parse(item.data))},200,who.cookie);}catch(e){return privateResponse({error:e instanceof Error?e.message:'Черновик не найден'},404);}}
 const who=await actor();if(!who.admin)return privateResponse({error:'Только для администратора'},403);const rows=await db().prepare('SELECT id,data,status,created_at FROM connection_requests ORDER BY created_at DESC LIMIT 200').all();return privateResponse({requests:rows.results});
}

export async function POST(req:Request){
 try{
  sameOrigin(req);const body=await req.json() as Record<string,unknown>,action=typeof body.action==='string'?body.action:'';
  if(action){const who=draftGuest(req);await quota(who.key,'connect-draft',40);
   if(action==='saveStore'){
    const input=storeDraft.parse(body.data);await checkUploadOwnership(input.photos,who.key);const now=new Date().toISOString(),id=input.id||crypto.randomUUID();if(input.id)await ownedDraft(id,who.key);const previous=input.id?await db().prepare('SELECT data FROM shops WHERE id=?').bind(id).first<{data:string}>():null,old=previous?JSON.parse(previous.data):{};
    const shop:Shop={...old,id,name:input.name,category:input.category,description:old.description||'',contact:input.phone,phone:input.phone,email:old.email||'',city:input.city,street:input.street,lat:old.lat??null,lng:old.lng??null,hours:old.hours||'Уточнить часы работы',site:input.site,photos:input.photos,status:'reference',source:input.site||'',demo:false,ownerConfirmed:false,addressConfirmed:old.addressConfirmed||false,visibility:'draft'} as Shop;
    if(input.id)await db().prepare("UPDATE shops SET data=? WHERE id=? AND visibility='draft'").bind(JSON.stringify(shop),id).run();else await db().batch([db().prepare("INSERT INTO shops(id,owner,data,visibility) VALUES(?,NULL,?,'draft')").bind(id,JSON.stringify(shop)),db().prepare('INSERT INTO onboarding(store_id,created_by,created_at) VALUES(?,?,?)').bind(id,who.key,now)]);return privateResponse({id,shop},200,who.cookie);
   }
   if(action==='catalogImport'){
    const input=z.object({storeId:z.string().uuid(),catalogUrl:webUrl.refine(Boolean),catalogConsent:z.literal(true)}).parse(body);await ownedDraft(input.storeId,who.key);const url=allowedSource(input.catalogUrl);if(!url)throw new Error('Сайт сохранён в карточке. Автосбор с нового домена запустит администратор после проверки заявки.');await quota(who.key,'connect-catalog-import',5);const html=await fetchApprovedMerchantSource(input.catalogUrl);if(!html)throw new Error('Сайт не разрешает безопасное чтение или временно недоступен');const shop=JSON.parse((await db().prepare('SELECT data FROM shops WHERE id=?').bind(input.storeId).first<{data:string}>())!.data) as Shop,now=new Date().toISOString(),offers=extractOffers(html,input.catalogUrl,shop.city).filter(item=>item.kind==='product'&&item.site).slice(0,50);if(!offers.length)throw new Error('На странице не найдены структурированные товарные предложения');
    const ids:string[]=[];for(const hit of offers){const source=hit.site||input.catalogUrl,existing=await db().prepare('SELECT id FROM products WHERE store_id=? AND normalized_name=? AND source_url=?').bind(input.storeId,normalize(hit.title),source).first<{id:string}>();if(existing)continue;const id=crypto.randomUUID(),product={id,storeId:input.storeId,name:hit.title,category:shop.category,brand:'',model:'',description:hit.description||'Условия уточняйте у продавца.',features:'',price:hit.price,priceFrom:false,quantity:null,stockConfirmed:false,sku:'',published:false,photos:[],source,sourceUrl:source,sourceType:'catalog',checkedAt:hit.checkedAt||now,imageSource:hit.image||'',imagePermission:'Фото не копируется до подтверждения владельца.',keywords:hit.title,demo:false,importedSource:input.catalogUrl};await db().prepare('INSERT INTO products(id,store_id,published,data,normalized_name,source_type,source_url,checked_at) VALUES(?,?,0,?,?,?,?,?)').bind(id,input.storeId,JSON.stringify(product),normalize(hit.title),'catalog',source,Date.parse(product.checkedAt)||Date.now()).run();ids.push(id);}return privateResponse({count:ids.length,ids},200,who.cookie);
   }
   if(action==='preview'){const id=z.string().uuid().parse(body.storeId);await ownedDraft(id,who.key);return privateResponse({path:await previewPath(id)},200,who.cookie);}
   if(action==='submitDraft'){
    const id=z.string().uuid().parse(body.storeId),row=await ownedDraft(id,who.key),shop=JSON.parse(row.data) as Shop,count=await db().prepare('SELECT COUNT(*) AS count FROM products WHERE store_id=?').bind(id).first<{count:number}>();if(!count?.count)throw new Error('Добавьте хотя бы один товар');const existing=await db().prepare("SELECT id FROM connection_requests WHERE json_extract(data,'$.draftStoreId')=? AND status IN ('pending','contacted','approved')").bind(id).first<{id:string}>();if(existing)return privateResponse({ok:true,id:existing.id,path:await previewPath(id),alreadySubmitted:true},200,who.cookie);
    const requestId=crypto.randomUUID(),createdAt=new Date().toISOString(),buyer=await buyerIdentity(req),data:RequestData={name:shop.name,contact:shop.phone,preferredChannel:'phone',city:shop.city,category:shop.category,catalogUrl:shop.site,catalogConsent:!!shop.site,note:'Черновик магазина и товары заполнены в едином onboarding.',draftStoreId:id,buyerId:buyer?.id||null,registeredProvider:buyer?.provider||null};await db().batch([db().prepare("INSERT INTO connection_requests(id,data,status,created_at) VALUES(?,?,'pending',?)").bind(requestId,JSON.stringify(data),createdAt),db().prepare('UPDATE shops SET data=? WHERE id=?').bind(JSON.stringify({...shop,submissionStatus:'pending',submittedAt:createdAt}),id)]);const notification=await notifyConnectionRequest({id:requestId,name:shop.name,contact:shop.phone,city:shop.city,category:shop.category,catalogUrl:shop.site,note:data.note||'',preferredChannel:'phone',createdAt});return privateResponse({ok:true,id:requestId,path:await previewPath(id),notification},200,who.cookie);
   }
   throw new Error('Неизвестное действие');
  }
  const b=z.object({name:z.string().trim().min(2).max(200),contactPerson:z.string().trim().min(2).max(120),phone:z.string().trim().min(5).max(100),contact:z.string().trim().min(5).max(200),preferredChannel:z.enum(['telegram','max','phone','email']).default('phone'),city:z.string().trim().min(1).max(100),category:z.enum(categories),catalogUrl:webUrl.refine(value=>!value||!!merchantSource(value),'Нужна публичная HTTPS-ссылка на каталог'),catalogConsent:z.boolean().default(false),note:z.string().max(2000),consent:z.literal(true),website:z.string().max(0).optional()}).parse(body);const who=draftGuest(req);await quota(who.key,'connect',5);const id=crypto.randomUUID(),createdAt=new Date().toISOString(),buyer=await buyerIdentity(req),data={...b,note:[`Контактное лицо: ${b.contactPerson}`,`Телефон: ${b.phone}`,b.note].filter(Boolean).join('\n'),buyerId:buyer?.id||null,registeredProvider:buyer?.provider||null};await db().prepare("INSERT INTO connection_requests(id,data,status,created_at) VALUES(?,?,'pending',?)").bind(id,JSON.stringify(data),createdAt).run();const notification=await notifyConnectionRequest({id,name:b.name,contactPerson:b.contactPerson,phone:b.phone,contact:b.contact,city:b.city,category:b.category,catalogUrl:b.catalogUrl,note:b.note,preferredChannel:b.preferredChannel,createdAt});return privateResponse({ok:true,notification},200,who.cookie);
 }catch(e){return privateResponse({error:e instanceof z.ZodError?'Проверьте обязательные поля и ссылки':e instanceof Error?e.message:'Не удалось сохранить заявку'},400);}
}

export async function PATCH(req:Request){try{sameOrigin(req);const who=await actor();if(!who.admin||!who.user)return privateResponse({error:'Нет доступа'},403);const b=z.union([z.object({id:z.string().uuid(),status:z.enum(['pending','contacted','approved','closed'])}),z.object({id:z.string().uuid(),reply:z.string().trim().min(1).max(2000)}),z.object({id:z.string().uuid(),action:z.literal('approveCatalog')})]).parse(await req.json());const row=await db().prepare('SELECT data,status FROM connection_requests WHERE id=?').bind(b.id).first<{data:string;status:string}>();if(!row)return privateResponse({error:'Заявка не найдена'},404);const data=JSON.parse(row.data) as RequestData;if('status'in b){await db().prepare('UPDATE connection_requests SET status=? WHERE id=?').bind(b.status,b.id).run();return privateResponse({ok:true});}
 if('action'in b){if(data.draftStoreId)return privateResponse({ok:true,storeId:data.draftStoreId,alreadyCreated:true});if(!data.catalogUrl||!data.catalogConsent||!merchantSource(data.catalogUrl))return privateResponse({error:'В заявке нет разрешённого публичного каталога'},400);const html=await fetchApprovedMerchantSource(data.catalogUrl);if(!html)return privateResponse({error:'Каталог не разрешает безопасное чтение или временно недоступен'},422);const offers=extractOffers(html,data.catalogUrl,data.city||'').filter(x=>x.kind==='product'&&x.site).slice(0,20);if(!offers.length)return privateResponse({error:'На странице не найдены структурированные товарные предложения'},422);const d=db(),now=new Date().toISOString(),storeId=crypto.randomUUID(),origin=new URL(data.catalogUrl).origin,shop={id:storeId,name:data.name||'Новый магазин',category:data.category||categories[0],description:'Черновик создан из заявки. Проверьте данные до публикации.',contact:data.contact||'',phone:'',email:'',city:data.city||'',street:'',lat:null,lng:null,hours:'Уточнить часы работы',site:origin,photos:[],status:'reference',source:data.catalogUrl,demo:false,personalDemo:true,ownerConfirmed:false,addressConfirmed:false,checkedAt:now,notes:'Автосбор разрешён администратором после заявки '+b.id};await d.batch([d.prepare("INSERT INTO shops(id,owner,data,visibility) VALUES(?,NULL,?,'draft')").bind(storeId,JSON.stringify(shop)),d.prepare('INSERT INTO onboarding(store_id,created_by,created_at) VALUES(?,?,?)').bind(storeId,who.user.userId,now),...offers.map((hit,index)=>{const id=crypto.randomUUID(),product={id,storeId,name:hit.title,category:data.category||categories[0],brand:'',model:'',description:hit.description||'Условия уточняйте у продавца.',features:'',price:hit.price,priceFrom:false,quantity:null,stockConfirmed:false,sku:'',published:false,photos:[],source:hit.site||data.catalogUrl,checkedAt:hit.checkedAt||now,imageSource:hit.image||'',keywords:hit.title,demo:false,importedSource:data.catalogUrl,importedRequestId:b.id,importedIndex:index};return d.prepare('INSERT INTO products(id,store_id,published,data) VALUES(?,?,0,?)').bind(id,storeId,JSON.stringify(product));})]);data.draftStoreId=storeId;data.catalogImport={count:offers.length,at:now};await d.prepare("UPDATE connection_requests SET data=?,status='approved' WHERE id=?").bind(JSON.stringify(data),b.id).run();return privateResponse({ok:true,storeId,count:offers.length});}
 const [provider,subject]=String(data.buyerId||'').split(':',2);if(!subject||!['telegram','max'].includes(provider))return privateResponse({error:'Заявитель не входил через Telegram или MAX. Используйте оставленный контакт.'},400);if(!await sendConnectionReply(provider,subject,data.name||'магазин',b.reply))return privateResponse({error:'Бот заявителя сейчас недоступен'},503);data.replies=[...(data.replies||[]).slice(-9),{text:b.reply,at:new Date().toISOString()}];await db().prepare("UPDATE connection_requests SET data=?,status='contacted' WHERE id=?").bind(JSON.stringify(data),b.id).run();return privateResponse({ok:true});}catch(e){return Response.json({error:e instanceof z.ZodError?'Проверьте ответ':e instanceof Error?e.message:'Не удалось обновить заявку'},{status:400,headers:privateHeaders});}}
