import {z} from 'zod';
import {db} from '@/db';
import {actor,sameOrigin} from '@/lib/onboarding';
import {guest,quota,privateResponse} from '@/lib/discovery-server';
import {notifyConnectionRequest,sendConnectionReply} from '@/lib/connection-notify';
import {buyerIdentity} from '@/lib/buyer-auth';
import {categories} from '@/lib/model';
import {merchantSource,fetchApprovedMerchantSource} from '@/lib/source-fetch';
import {extractOffers} from '@/lib/offer-extraction';

type RequestData={name?:string;city?:string;category?:string;catalogUrl?:string;catalogConsent?:boolean;contact?:string;buyerId?:string|null;registeredProvider?:string|null;replies?:{text:string;at:string}[];draftStoreId?:string;catalogImport?:{count:number;at:string}};

export async function GET(){const who=await actor();if(!who.admin)return privateResponse({error:'Только для администратора'},403);const rows=await db().prepare('SELECT id,data,status,created_at FROM connection_requests ORDER BY created_at DESC LIMIT 200').all();return privateResponse({requests:rows.results});}

export async function POST(req:Request){try{sameOrigin(req);const b=z.object({name:z.string().trim().min(2).max(200),contact:z.string().trim().min(5).max(200),preferredChannel:z.enum(['telegram','max','phone','email']).default('phone'),city:z.string().trim().min(1).max(100),category:z.enum(categories),catalogUrl:z.union([z.literal(''),z.string().url().max(1000)]).refine(v=>!v||!!merchantSource(v),'Нужна публичная HTTPS-ссылка на каталог'),catalogConsent:z.boolean().default(false),note:z.string().max(2000),consent:z.literal(true),website:z.string().max(0).optional()}).parse(await req.json());const who=await guest(req);await quota(who.key,'connect',5);const id=crypto.randomUUID(),createdAt=new Date().toISOString(),buyer=await buyerIdentity(req);const data={...b,buyerId:buyer?.id||null,registeredProvider:buyer?.provider||null};await db().prepare("INSERT INTO connection_requests (id,data,status,created_at) VALUES (?,?,'pending',?)").bind(id,JSON.stringify(data),createdAt).run();const notification=await notifyConnectionRequest({id,name:b.name,contact:b.contact,city:b.city,category:b.category,catalogUrl:b.catalogUrl,note:b.note,preferredChannel:b.preferredChannel,createdAt});return privateResponse({ok:true,notification},200,who.cookie);}catch(e){return privateResponse({error:e instanceof z.ZodError?'Проверьте название, категорию, каталог, контакт и согласия':e instanceof Error?e.message:'Не удалось отправить заявку'},400);}}

export async function PATCH(req:Request){try{sameOrigin(req);const who=await actor();if(!who.admin||!who.user)return privateResponse({error:'Нет доступа'},403);const b=z.union([z.object({id:z.string().uuid(),status:z.enum(['pending','contacted','approved','closed'])}),z.object({id:z.string().uuid(),reply:z.string().trim().min(1).max(2000)}),z.object({id:z.string().uuid(),action:z.literal('approveCatalog')})]).parse(await req.json());const row=await db().prepare('SELECT data,status FROM connection_requests WHERE id=?').bind(b.id).first<{data:string;status:string}>();if(!row)return privateResponse({error:'Заявка не найдена'},404);const data=JSON.parse(row.data) as RequestData;
 if('status'in b){await db().prepare('UPDATE connection_requests SET status=? WHERE id=?').bind(b.status,b.id).run();return privateResponse({ok:true});}
 if('action'in b){if(!data.catalogUrl||!data.catalogConsent||!merchantSource(data.catalogUrl))return privateResponse({error:'В заявке нет разрешённого публичного каталога'},400);const html=await fetchApprovedMerchantSource(data.catalogUrl);if(!html)return privateResponse({error:'Каталог не разрешает безопасное чтение или временно недоступен'},422);const offers=extractOffers(html,data.catalogUrl,data.city||'').filter(x=>x.kind==='product'&&x.site).slice(0,20);if(!offers.length)return privateResponse({error:'На указанной странице не найдены структурированные товарные предложения'},422);const d=db(),now=new Date().toISOString(),storeId=data.draftStoreId||crypto.randomUUID(),origin=new URL(data.catalogUrl).origin;
  if(!data.draftStoreId){const shop={id:storeId,name:data.name||'Новый магазин',category:data.category||categories[0],description:'Черновик создан из заявки. Проверьте данные до публикации.',contact:data.contact||'',phone:'',email:'',city:data.city||'',street:'',lat:null,lng:null,hours:'Уточнить часы работы',site:origin,photos:[],status:'reference',source:data.catalogUrl,demo:false,personalDemo:true,ownerConfirmed:false,addressConfirmed:false,checkedAt:now,notes:'Автосбор разрешён администратором после заявки '+b.id};await d.batch([d.prepare("INSERT INTO shops(id,owner,data,visibility) VALUES (?,NULL,?,'draft')").bind(storeId,JSON.stringify(shop)),d.prepare('INSERT INTO onboarding(store_id,created_by,created_at) VALUES (?,?,?)').bind(storeId,who.user.userId,now)]);}else await d.prepare("DELETE FROM products WHERE store_id=? AND json_extract(data,'$.importedRequestId')=?").bind(storeId,b.id).run();
  const statements=offers.map((hit,index)=>{const id=crypto.randomUUID(),product={id,storeId,name:hit.title,category:data.category||categories[0],brand:'',model:'',description:hit.description||'Условия уточняйте у продавца.',features:'',price:hit.price,priceFrom:false,quantity:null,stockConfirmed:false,sku:'',published:false,photos:[],source:hit.site||data.catalogUrl,checkedAt:hit.checkedAt||now,imageSource:hit.image||'',imagePermission:'Изображение найдено в публичном каталоге, но не копируется и не публикуется до подтверждения владельца.',keywords:hit.title,testOnly:false,demo:false,importedSource:data.catalogUrl,importedRequestId:b.id,importedIndex:index};return d.prepare('INSERT INTO products(id,store_id,published,data) VALUES (?,?,0,?)').bind(id,storeId,JSON.stringify(product));});if(statements.length)await d.batch(statements);data.draftStoreId=storeId;data.catalogImport={count:offers.length,at:now};await d.prepare("UPDATE connection_requests SET data=?,status='approved' WHERE id=?").bind(JSON.stringify(data),b.id).run();return privateResponse({ok:true,storeId,count:offers.length});}
 const [provider,subject]=String(data.buyerId||'').split(':',2);if(!subject||!['telegram','max'].includes(provider))return privateResponse({error:'Заявитель не входил через Telegram или MAX. Используйте оставленный контакт.'},400);if(!await sendConnectionReply(provider,subject,data.name||'магазин',b.reply))return privateResponse({error:'Бот заявителя сейчас недоступен'},503);data.replies=[...(data.replies||[]).slice(-9),{text:b.reply,at:new Date().toISOString()}];await db().prepare("UPDATE connection_requests SET data=?,status='contacted' WHERE id=?").bind(JSON.stringify(data),b.id).run();return privateResponse({ok:true});}catch(e){return privateResponse({error:e instanceof z.ZodError?'Проверьте ответ':e instanceof Error?e.message:'Не удалось обновить заявку'},400);}}
