'use client';
import {useEffect,useState} from 'react';
import '../account/style.css';
type Row=Record<string,string|number>;
type Stats={costs:Row[];events:Row[];geography:Row[];conversion:Row;visitors:Row;applications:Row[];budget:Row;accounts:Row[];searches:Row[];topQueries:Row[];payments:Row[];sample:{count:number;averageMs:number|null;withCache:number;knownCostRub:number;unknownCostSearches:number};notes:string[]};
export default function LaunchStats(){const [data,setData]=useState<Stats|null>(null),[error,setError]=useState('');
 async function refresh(){setError('');try{const r=await fetch('/api/launch-stats',{cache:'no-store'});const b=await r.json() as Stats&{error?:string};if(!r.ok)throw Error(b.error||'Ошибка');setData(b);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void refresh();},[]);
 return <main className="buyer-account"><a href="/">← НайдиGo</a><h1>Статистика запуска</h1><p>Закрытая сводка за 30 дней. Персональные контакты здесь не отображаются.</p><button onClick={()=>void refresh()}>Обновить</button><p><a href="https://metrika.yandex.ru/dashboard?id=113120246" target="_blank" rel="noreferrer">Открыть Яндекс Метрику ↗</a></p>{error&&<p role="alert">{error}</p>}{data&&<><section><h2>Посетители</h2><p>{Object.entries(data.visitors||{}).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><p>Это уникальные браузеры по анонимному cookie; Метрика остаётся основным источником аудитории.</p></section><section><h2>Поиск — выборка {data.sample.count}</h2><p>Среднее время: {data.sample.averageMs===null?'нет данных':(data.sample.averageMs/1000).toFixed(2)+' с'}. С использованием кеша: {data.sample.withCache}.</p><p>Известные расходы выборки: {data.sample.knownCostRub.toFixed(2)} ₽. С неполным учётом: {data.sample.unknownCostSearches}.</p></section>{[['Заявки магазинов',data.applications],['Бюджет API',[data.budget]],['Стоимость по моделям',data.costs],['Города и категории',data.geography],['Действия покупателей',data.events],['Оплаченные аккаунты и реальная выручка',[data.conversion]],['Регистрации',data.accounts],['Операции поиска',data.searches],['Топ запросов',data.topQueries],['Платежи (test=1 — тест)',data.payments]].map(([title,rows])=><section key={String(title)}><h2>{String(title)}</h2>{(rows as Row[]).length?(rows as Row[]).map((row,i)=><p key={i}>{Object.entries(row).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p>):<p>Пока нет данных</p>}</section>)}{data.notes.map(n=><p key={n}>{n}</p>)}</>}</main>;
}
