import {z} from 'zod';
import {db} from '@/db';
import {sameOrigin} from '@/lib/onboarding';
import {guest,quota,privateResponse,planWithAI,searchLocal} from '@/lib/discovery-server';
import type {ShoppingPlan} from '@/lib/discovery';
import {runSearch} from '@/lib/search-engine';
import {hitShop} from '@/lib/city-search';
const item=z.object({id:z.string().min(1).max(80),category:z.string().max(100),name:z.string().trim().min(1).max(200),query:z.string().trim().min(1).max(200),note:z.string().max(400),enabled:z.boolean()});
export async function GET(req:Request){const who=await guest(req);const id=new URL(req.url).searchParams.get('id');if(!id)return privateResponse({error:'Подборка не указана'},400,who.cookie);const row=await db().prepare('SELECT data FROM shopping_plans WHERE id=? AND owner=?').bind(id,who.key).first<{data:string}>();return row?privateResponse({plan:JSON.parse(row.data)},200,who.cookie):privateResponse({error:'Подборка не найдена в этом браузере'},404,who.cookie);}
export async function POST(req:Request){try{sameOrigin(req);const who=await guest(req);await quota(who.key,'plans',60);const b=z.object({action:z.enum(['create','save','generate','match']),id:z.string().uuid().optional(),task:z.string().trim().max(4000).optional(),city:z.string().trim().min(1).max(100).optional(),items:z.array(item).max(30).optional()}).parse(await req.json());let plan:ShoppingPlan;if(b.action==='create'){plan={id:crypto.randomUUID(),title:(b.task||'Моя подборка').slice(0,180),task:b.task||'',city:b.city||'Казань',items:[],questions:[],ai:false,updatedAt:new Date().toISOString()};await db().prepare('INSERT INTO shopping_plans (id,owner,data) VALUES (?,?,?)').bind(plan.id,who.key,JSON.stringify(plan)).run();return privateResponse({plan},200,who.cookie);}const row=await db().prepare('SELECT data FROM shopping_plans WHERE id=? AND owner=?').bind(b.id||'',who.key).first<{data:string}>();if(!row)return privateResponse({error:'Нет доступа к подборке'},404,who.cookie);plan=JSON.parse(row.data);if(b.action==='match'){const matches=[];for(const i of plan.items.filter(i=>i.enabled).slice(0,6)){const result=await runSearch({query:i.query,city:plan.city});matches.push({itemId:i.id,offers:[],stores:result.hits.filter(h=>h.point&&h.address).map(hitShop),hits:result.hits,warnings:result.warnings});}return privateResponse({matches},200,who.cookie);}if(b.action==='generate'){await quota('global','ai',20);const result=await planWithAI(b.task||plan.task,plan.city,plan.items);plan={...plan,title:result.title,task:b.task||plan.task,questions:result.questions,items:result.items.map(i=>({...i,id:crypto.randomUUID(),enabled:true})),ai:true};}else{if(b.items)plan.items=b.items;if(b.task!==undefined)plan.task=b.task;if(b.city)plan.city=b.city;}plan.updatedAt=new Date().toISOString();await db().prepare('UPDATE shopping_plans SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(plan),plan.id,who.key).run();return privateResponse({plan},200,who.cookie);}catch(e){return privateResponse({error:e instanceof z.ZodError?'Проверьте состав подборки':e instanceof Error?e.message:'Не удалось сохранить подборку'},400);}}
