'use client';
import {useEffect,useState} from 'react';
import './style.css';
import PersonalSync from './personal-sync';
type State={user:{name:string;provider:string}|null;providers:{email:boolean;yandex:boolean;telegram:boolean;max:boolean};balance:{kind:string;remaining:number;expiresAt:number|null}[];orders:{id:string;amount:number;status:string;test:number}[];pro:{price:number;searches:number;days:number};payments:boolean;test:boolean;free:number;quota:boolean};
export default function Account(){const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[link,setLink]=useState(''),[note,setNote]=useState('');
 async function refresh(){const r=await fetch('/api/buyer/me');const b=await r.json() as State&{error?:string};if(!r.ok)throw Error(b.error);setData(b);}
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.has('login_error'))setError('Вход через Яндекс не завершён. Попробуйте снова.');if(params.has('login_error'))history.replaceState(null,'','/account');refresh().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!link)return;let stopped=false,inflight=false;const until=Date.now()+300000;async function poll(){if(stopped||inflight||document.hidden)return;if(Date.now()>until){stopped=true;setLink('');setNote('Срок подтверждения истёк. Начните вход ещё раз.');return;}inflight=true;try{const r=await post('/api/buyer/auth',{action:'status'});if(r.authenticated&&!stopped){stopped=true;setLink('');setNote('Вы вошли. Можно вернуться к поиску.');await refresh();}}catch{}finally{inflight=false;}}const timer=setInterval(poll,2500);void poll();return()=>{stopped=true;clearInterval(timer);};},[link]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function post(url:string,body:unknown){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json() as {error?:string;url:string;status:string;message?:string;authenticated?:boolean};if(!r.ok)throw Error(b.error||'Не удалось выполнить действие');return b;}
 return <main className="buyer-account"><a href="/#home">← НайдиGo · К поиску</a><h1>Аккаунт и тариф</h1>{error&&<p role="alert">{error}</p>}{note&&<p role="status">{note}</p>}{!data?<p>Загружаем…</p>:<>
 {!data.user?<section><h2>Войти без пароля</h2><p>Выберите удобный способ. Поиск работает и без регистрации.</p>{data.providers.yandex&&<button disabled={busy} onClick={()=>action(async()=>{const b=await post('/api/buyer/yandex',{});location.assign(b.url);})}>Войти через Яндекс</button>}{(['telegram','max'] as const).map(p=><button key={p} disabled={busy||!data.providers[p]} onClick={()=>action(async()=>{const b=await post('/api/buyer/auth',{provider:p});setLink(b.url);})}>{p==='telegram'?'Войти через Telegram':'Войти через MAX'}{!data.providers[p]?' — пока недоступен':''}</button>)}{link&&<><p><a href={link} target="_blank" rel="noreferrer">Открыть бота и подтвердить вход ↗</a></p><p role="status">Ждём подтверждения. После нажатия кнопки в боте вернитесь в этот браузер. Ссылка действует 5 минут.</p></>}</section>:<section><h2>{data.user.name}</h2><p>Вход через {data.user.provider}. Аккаунты разных способов входа пока отдельные.</p>{data.balance.map(b=><p key={b.kind}>{b.kind==='free'?'Free':'Pro'}: осталось {b.remaining} поисков{b.expiresAt?' · до '+new Date(b.expiresAt).toLocaleDateString('ru-RU'):''}</p>)}<button disabled={busy} onClick={()=>action(async()=>{const r=await fetch('/api/buyer/auth',{method:'DELETE'});if(!r.ok)throw Error('Не удалось выйти');await refresh();})}>Выйти</button></section>}
 {data.user&&<PersonalSync/>}<section><h2>Free</h2>{!data.user&&<p>На этом устройстве осталось: {data.balance.filter(b=>b.kind==='free').reduce((n,b)=>n+b.remaining,0)} поисков.</p>}<p>{data.free} поисков разово. Просмотр карточек и открытие карты бесплатны. Поиск товаров по дороге расходует один поиск.</p>{!data.quota&&<p>Учёт лимита ещё не включён.</p>}</section>
 <section><h2>Pro — {data.pro.price/100} ₽</h2><p>{data.pro.searches} поисков на {data.pro.days} дней. Без автопродления. Неиспользованные поиски истекают вместе с пакетом.</p>{data.test&&<p><strong>Тестовая оплата. Реальные деньги не списываются.</strong></p>}<button disabled={busy||!data.user||!data.payments} onClick={()=>action(async()=>{const b=await post('/api/buyer/payments',{});location.assign(b.url);})}>{data.test?'Проверить тестовую оплату':'Оплатить Pro'}</button>{!data.user&&<p>Для оплаты сначала войдите.</p>}</section>
 {!!data.orders.length&&<section><h2>Платежи</h2>{data.orders.map(o=><article key={o.id}><p>{o.test?'Тест · ':''}{o.amount/100} ₽ · {o.status}</p><button disabled={busy} onClick={()=>action(async()=>{const b=await post('/api/buyer/payments',{id:o.id});setNote(b.status==='succeeded'?'Оплата подтверждена, пакет начислен. Повторная проверка не начисляет его второй раз.':'Статус: '+b.status);await refresh();})}>Проверить оплату</button></article>)}</section>}
 <p>Избранное и история хранятся на устройстве; после входа можно перенести копию в аккаунт. <a href="/#my">Открыть «Моё»</a></p></>}</main>;
}
