import {env} from 'cloudflare:workers';
import {db} from '@/db';
import {generatePlan} from './plan-ai';
import {routerCall} from './router-gateway';
import {hash,token} from './onboarding';
import {localDiscovery,safeUrl,type WebSource,type PlanItem} from './discovery';
import type {Product,Shop} from './model';
export async function publicIndex(){const shops=await db().prepare("SELECT data,visibility FROM shops WHERE visibility='public' AND COALESCE(json_extract(data,'$.demo'),0)=0").all<{data:string;visibility:'public'}>();const products=await db().prepare("SELECT p.data FROM products p JOIN shops s ON s.id=p.store_id WHERE p.published=1 AND s.visibility='public' AND COALESCE(json_extract(p.data,'$.demo'),0)=0 AND COALESCE(json_extract(p.data,'$.testOnly'),0)=0 AND COALESCE(json_extract(s.data,'$.demo'),0)=0").all<{data:string}>();return {shops:shops.results.map(r=>{const s={...JSON.parse(r.data),visibility:r.visibility};delete s.notes;delete s.contact;return s as Shop;}),products:products.results.map(r=>JSON.parse(r.data) as Product)};}
export async function searchLocal(query:string,city:string,near?:{lat:number;lng:number}){const index=await publicIndex();return localDiscovery(index.products,index.shops,query,city,near);}
export async function guest(req:Request){const old=req.headers.get('cookie')?.match(/(?:^|;\s*)ng_client=([a-f0-9]{64})/)?.[1];const value=old||token();return {key:await hash(value),cookie:old?null:`ng_client=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${new URL(req.url).protocol==='https:'?'; Secure':''}`};}
export const privateResponse=(body:unknown,status=200,cookie?:string|null)=>Response.json(body,{status,headers:{'Cache-Control':'private, no-store',...(cookie?{'Set-Cookie':cookie}:{})}});
// Durable, atomic hourly quotas prevent anonymous paid API calls from being unbounded.
export async function quota(key:string,action:string,limit:number){const id=`${key}:${action}:${Math.floor(Date.now()/3600000)}`;const row=await db().prepare('INSERT INTO discovery_limits (id,count) VALUES (?,1) ON CONFLICT(id) DO UPDATE SET count=count+1 WHERE count<? RETURNING count').bind(id,limit).first();if(!row)throw new Error('Лимит запросов на этот час исчерпан. Попробуйте позже.');}
export async function externalSearch(query:string,city:string):Promise<WebSource[]>{if(!env.BRAVE_SEARCH_API_KEY)return [];const url=new URL('https://api.search.brave.com/res/v1/web/search');url.search=new URLSearchParams({q:`${query} ${city}`,count:'8',search_lang:'ru',result_filter:'web'}).toString();const r=await fetch(url,{headers:{'X-Subscription-Token':env.BRAVE_SEARCH_API_KEY,'Accept':'application/json'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('Внешний поиск временно недоступен');const b=await r.json() as {web?:{results?:{title:string;url:string;description?:string}[]}};return (b.web?.results||[]).filter(x=>safeUrl(x.url)).map(x=>({title:x.title.replace(/<[^>]*>/g,''),url:x.url,description:(x.description||'').replace(/<[^>]*>/g,''),checkedAt:new Date().toISOString(),status:'page-only',address:null,price:null}));}
export async function planWithAI(task:string,city:string,existing:PlanItem[]){return generatePlan({key:env.ROUTERAI_API_KEY,model:env.ROUTERAI_MODEL},task,city,existing,async(_url,init)=>Response.json(await routerCall(JSON.parse(String(init?.body)))));}
