import {categories,type Shop,type Product} from './model';
const image=(p:string)=>`https://cdn.dummyjson.com/product-images/${p}/thumbnail.webp`;
export const seedShops:Shop[]=['Дом рядом','Городской выбор','Сад и хвост'].map((name,i)=>({id:`demo-s${i}`,name,category:categories[i*2],description:'Вымышленный магазин для демонстрации сервиса. Адрес — пример, не место реальной торговли.',contact:'Демо',phone:'+7 000 000-00-00',email:'demo@example.com',city:'Казань',street:['ул. Петербургская, 12','ул. Чистопольская, 25','ул. Декабристов, 85'][i],lat:[55.7845,55.8176,55.8267][i],lng:[49.1244,49.1245,49.0904][i],hours:'Ежедневно, 10:00–20:00',site:'',photos:[],status:i===1?'reference':'connected',source:'Синтетические демо-данные. Не получены из публичного справочника.',demo:true}));
type Entry=[string,number,string,string];
const rows:Entry[][]=[
 [['Настольная лампа',2490,'home-decoration/table-lamp','светильник свет стол'],['Декоративная фоторамка',890,'home-decoration/family-tree-photo-frame','семья интерьер'],['Кухонная сковорода',1790,'kitchen-accessories/pan','посуда жарка кухня'],['Разделочная доска',690,'kitchen-accessories/chopping-board','кухня дерево'],['Погружной блендер',2990,'kitchen-accessories/hand-blender','измельчитель кухня']],
 [['Компрессор для шин',3990,'https://wekampa.com/cdn/shop/files/51OTf7FsT6L._AC_SL1500.webp?v=1692537260','насос автомобиль подкачка'],['Держатель телефона BOROFONE',990,'https://borofone-hoco.ru/upload/iblock/ee2/isze6zxiboyz2xam1h2g2wwid4kkefj0.jpg','авто смартфон'],['Автомобильный пылесос',2190,'https://image.galacentre.ru/size/1000/1eb837c0-0cfd-463a-9e3b-432bb8ab43bd/3.jpg','машина уборка'],['Органайзер в багажник',1590,'https://m.media-amazon.com/images/I/71QhPscd7JL._AC_UL960_QL65_.jpg','автомобиль хранение'],['Автомобильная USB зарядка',590,'https://erdshop.com/cdn/shop/files/1.CC-111MobileChargerUSB-ADOCK1.webp?v=1737461329','машина питание телефон']],
 [['Мяч баскетбольный',1890,'sports-accessories/basketball','баскетбол спорт'],['Мяч футбольный',1490,'sports-accessories/football','футбол спорт'],['Теннисная ракетка',3490,'sports-accessories/tennis-racket','теннис спорт'],['Волейбольный мяч',1590,'sports-accessories/volleyball','волейбол спорт'],['Волан для бадминтона',290,'sports-accessories/feather-shuttlecock','бадминтон перо']],
 [['Наушники AirPods Max',49990,'mobile-accessories/apple-airpods-max-silver','bluetooth беспроводные гарнитура шумоподавление серебристый'],['Наушники AirPods',14990,'mobile-accessories/apple-airpods','блютуз беспроводные белый'],['Умная колонка HomePod mini',12990,'mobile-accessories/apple-homepod-mini-cosmic-grey','звук bluetooth'],['Зарядная станция AirPower',4990,'mobile-accessories/apple-airpower-wireless-charger','зарядка беспроводная'],['Ноутбук MacBook Pro 14',159990,'laptops/apple-macbook-pro-14-inch-space-grey','компьютер ноутбук экран']],
 [['Кашпо с растением',890,'home-decoration/plant-pot','горшок цветы'],['Садовая лейка 10 л',790,'https://media.screwfix.com/is/image/ae235/920YU_P','полив вода'],['Секатор садовый',1590,'https://www.bootstrapfarmer.com/cdn/shop/files/Pruner_Bypass_Red_Line_Full_Size_Open_1600x.jpg?v=1731347538','ножницы обрезка ветки'],['Перчатки садовые',390,'https://www.workgloves.co.uk/user/products/briers-multi-grip-all-rounder-gardening-gloves-ac-1%283%29.jpg','защита руки'],['Совок садовый',690,'https://cdn.nationaltrust.org.uk/media/catalog/product/cache/deb52ac916afe485d27f1837f6a5dd06/t/r/trowel-cutout-01.jpg?auto=webp','лопатка посадка земля']],
 [['Лежанка для собаки',3290,'https://www.allpetsolutions.co.uk/cdn/shop/files/Untitled_18.png?v=1712767804&width=1080','подстилка питомец собака'],['Миска для питомца',490,'https://www.promocionalesdelcentro.mx/24105/PLATO-MEALTIME-PARA-PERRO-MASCOTA-PROMOCIONAL-PET005.jpg','корм вода собака кошка'],['Поводок для собак',1290,'https://cdn.shopify.com/s/files/1/0936/5484/3766/files/Hurtta-Hundeleine-Seeker-Standard-Leash-honey_110802_1_5_7p.jpg?v=1773217737','прогулка щенок'],['Когтеточка с игрушкой',2490,'https://www.petessentialswarehouse.co.nz/cdn/shop/files/AM505_Grey__19671_600x.webp?v=1684214316','кот кошка котенок'],['Мяч для собак',590,'https://ollydog.com/cdn/shop/files/OllyDog_Happy_Camper_Ball_Rubber_Fetch_Bounce_Yellow.png?crop=center&height=1200&v=1747196789&width=1200','игрушка щенок собака']]
];
export const seedProducts:Product[]=rows.flatMap((row,c)=>row.map(([name,price,photo,keywords],i)=>({id:`demo-p${c*5+i}`,storeId:`demo-s${Math.floor(c/2)}`,name,price,category:categories[c],brand:'',model:'',description:'Демонстрационная карточка. Цена, характеристики и количество приведены для проверки сервиса, не являются предложением продажи.',features:keywords,quantity:i===4?0:i===1?2:8,sku:`DEMO-${c*5+i}`,published:true,photos:[photo.startsWith('https:')?photo:image(photo)],keywords,demo:true})));
