import type {SearchHit} from './city-search';
const decode=(s:string)=>s.replace(/&quot;/g,'"').replace(/&#39;|&#x27;/g,"'").replace(/&nbsp;/g,' ').replace(/&amp;/g,'&');
const text=(s:string)=>decode(s.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim());
const attr=(tag:string,name:string)=>decode(tag.match(new RegExp('\\b'+name+'\\s*=\\s*["\']([^"\']*)["\']','i'))?.[1]||'');
// Balanced div boundaries: never associate a price from the next product with this title.
export function sellerBlocks(html:string,className:string){
 const clean=html.replace(/<script\b[\s\S]*?<\/script\s*>|<style\b[\s\S]*?<\/style\s*>|<!--[\s\S]*?-->/gi,'');
 const tags=[...clean.matchAll(/<\/?div\b[^>]*>/gi)],out:string[]=[];
 for(let i=0;i<tags.length&&out.length<24;i++){
  if(tags[i][0].startsWith('</')||!attr(tags[i][0],'class').split(/\s+/).includes(className))continue;
  let depth=1,j=i+1;for(;j<tags.length&&depth;j++)depth+=tags[j][0].startsWith('</')?-1:1;
  if(!depth){out.push(clean.slice(tags[i].index,tags[j-1].index!+tags[j-1][0].length));i=j-1;}
 }
 return out;
}
export function sellerOffers(html:string,source:string,city:string,checkedAt=new Date().toISOString()):SearchHit[]{
 const host=new URL(source).hostname,pet=host==='kazan.gomeovet.ru';
 if(host==='kazan.tatmetiz.ru')return tatmetizOffers(html,source,city,checkedAt);
 if(host==='megakrepezh.ru'||host==='www.megakrepezh.ru')return megaKrepezhOffers(html,source,city,checkedAt);
 if(host==='kazan.novocraft.ru')return novocraftOffers(html,source,city,checkedAt);
 if(host==='skskazan.ru'||host==='www.skskazan.ru')return sksOffers(html,source,city,checkedAt);
 if(host==='autocraft-kzn.ru'||host==='www.autocraft-kzn.ru')return autocraftOffers(html,source,city,checkedAt);
 if(host==='gazzap116.ru'||host==='www.gazzap116.ru')return gazzapOffers(html,source,city,checkedAt);
 if(host==='makpets.ru'||host==='www.makpets.ru')return makpetsOffers(html,source,city,checkedAt);
 if(host==='biosfera-kazan.ru'||host==='www.biosfera-kazan.ru')return biosferaOffers(html,source,city,checkedAt);
 if(host==='maikorcos.com'||host==='www.maikorcos.com')return maikorcosOffers(html,source,city,checkedAt);
 if(host==='koreavisage.ru'||host==='www.koreavisage.ru')return koreaVisageOffers(html,source,city,checkedAt);
 if(!pet&&!['velosky.ru','kazan-mall.istudio-kazan.ru'].includes(host))return [];
 const container=pet?'product-thumb':host==='kazan-mall.istudio-kazan.ru'||host==='velosky.ru'?'item_block':'item_info';
 const productBlocks=sellerBlocks(html,container);
 // Older Velosky fixtures/pages exposed only item_info. The live catalog keeps
 // the lazy-loaded image in the surrounding item_block, so prefer that block.
 const blocks=host==='velosky.ru'&&!productBlocks.length?sellerBlocks(html,'item_info'):productBlocks;
 return blocks.flatMap(block=>{
  const titleBlock=sellerBlocks(block,pet?'product-name':'item-title')[0]||'';
  const link=titleBlock.match(/<a\b([^>]*)>([\s\S]*?)<\/a>/i);if(!link)return [];
  const title=text(link[2]);let site:URL;try{site=new URL(attr(link[1],'href'),source);}catch{return [];}
  if(!title||site.hostname!==host||site.protocol!=='https:')return [];
  const prices=pet?[...block.matchAll(/<span\b[^>]*>[\s\S]*?<\/span>/gi)].filter(m=>/\bcalc-price\d+\b/.test(attr(m[0],'class'))&&/₽/.test(m[0])).map(m=>attr(m[0],'data-price')):
   [...block.matchAll(/<div\b[^>]*>/gi)].filter(m=>{const classes=attr(m[0],'class').split(/\s+/);return classes.includes('price')&&!classes.includes('discount')&&attr(m[0],'data-currency')==='RUB';}).map(m=>attr(m[0],'data-value'));
  const values=[...new Set(prices.filter(p=>/^\d+(?:\.\d+)?$/.test(p)).map(Number))];
  const price=values.length===1&&values[0]>0&&values[0]<=1e9?values[0]:null;
  const variant=pet?block.match(/<option\b[^>]*\bselected[^>]*>([^<]+)<\/option>/i)?.[1]:null;
  const imageTags=[...block.matchAll(/<img\b[^>]*>/gi)].map(match=>match[0]);
  const rawImage=imageTags.map(tag=>attr(tag,'data-src')||attr(tag,'data-lazy-src')||attr(tag,'src')).find(value=>value&&!/^data:/i.test(value)&&/\.(?:avif|webp|png|jpe?g)(?:\?|$)/i.test(value))||'';let image:string|null=null;
  try{if(rawImage){const imageURL=new URL(rawImage,source);if(imageURL.protocol==='https:'&&imageURL.hostname===host)image=imageURL.href;}}catch{}
  return [{id:'seller-offer:'+site.href,kind:'product',title,description:variant?'Цена для варианта: '+text(variant):'Условия опубликованной цены уточняйте у продавца.',category:'',city,address:null,point:null,phone:null,site:site.href,hours:null,source:site.href,checkedAt,price,image,status:'website',distanceKm:null,seller:pet?'Гомеовет':host==='velosky.ru'?'Velosky':'iStudio',currency:price===null?null:'RUB',priceEvidence:price===null?null:'Цена в товарном блоке каталога продавца',evidence:'source-page',sourceAvailability:'unknown'} satisfies SearchHit];
 });
}

function blocksFromStarts(html:string,pattern:RegExp,limit=24){const matches=[...html.matchAll(pattern)],out:string[]=[];for(let i=0;i<matches.length&&out.length<limit;i++)out.push(html.slice(matches[i].index,matches[i+1]?.index??html.length));return out;}
function absolute(raw:string,source:string,image=false){try{const url=new URL(raw,source),host=new URL(source).hostname,assetHosts=new Set(['m-files.cdn1.cc','cdn-st3.vigbo.com','cdn.insales-shop.ru']);if(url.protocol!=='https:'||url.hostname!==host&&!(image&&assetHosts.has(url.hostname)))return null;if(image&&!/\.(?:avif|webp|png|jpe?g)(?:@(?:avif|webp|png|jpe?g))?(?:\?|$)/i.test(url.href))return null;return url.href;}catch{return null;}}
function observed(raw:string){const value=Number(raw.replace(/\s/g,'').replace(',','.'));return Number.isFinite(value)&&value>0&&value<=1e9?value:null;}
function hit(source:string,city:string,checkedAt:string,data:{title:string;link:string;image?:string;price:number|null;seller:string;availability?:'in_stock'|'out_of_stock'|'unknown';category?:string;address?:string;phone?:string}):SearchHit[]{const site=absolute(data.link,source),image=data.image?absolute(data.image,source,true):null;if(!site||!data.title)return [];return [{id:'seller-offer:'+site,kind:'product',title:text(data.title),description:'Условия опубликованной цены и выдачи уточняйте у продавца.',category:data.category||'Дом и ремонт',city,address:data.address||null,point:null,phone:data.phone||null,site,hours:null,source:site,checkedAt,price:data.price,image,status:'website',distanceKm:null,seller:data.seller,currency:data.price===null?null:'RUB',priceEvidence:data.price===null?null:'Цена в товарном блоке каталога продавца',evidence:'source-page',locationEvidence:'regional-catalog',sourceAvailability:data.availability||'unknown'}];}
function tatmetizOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<article\b[^>]*class=["'][^"']*\bgood\b[^"']*\bjs-good\b[^"']*["'][^>]*>/gi).flatMap(block=>{const opening=block.match(/<article\b[^>]*>/i)?.[0]||'',link=block.match(/<a\b[^>]*href=["']([^"']+)["'][^>]*class=["'][^"']*good__img-wrap/i)?.[1]||'',image=block.match(/<img\b[^>]*src=["']([^"']+)["']/i)?.[1]||'',title=attr(opening,'data-name'),price=observed(attr(opening,'data-price')),stock=attr(opening,'data-stock');return hit(source,city,checkedAt,{title,link,image,price,seller:'Татметиз',address:'ул. Фатыха Амирхана, 25, Казань',phone:'+7 843 250-72-44',availability:stock==='1'?'in_stock':'out_of_stock'});});}
function megaKrepezhOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<li\b[^>]*class=["'][^"']*\bproduct-container\b[^"']*["'][^>]*>/gi).flatMap(block=>{const linkTag=block.match(/<a\b[^>]*href=["'][^"']+["'][^>]*title=["'][^"']+["'][^>]*>/i)?.[0]||block.match(/<a\b[^>]*title=["'][^"']+["'][^>]*href=["'][^"']+["'][^>]*>/i)?.[0]||'',priceText=block.match(/<span\b[^>]*class=["'][^"']*PricesalesPrice[^"']*["'][^>]*>\s*([\d\s,.]+)\s*руб/iu)?.[1]||'';return hit(source,city,checkedAt,{title:attr(linkTag,'title'),link:attr(linkTag,'href'),image:block.match(/<img\b[^>]*src=["']([^"']+)["']/i)?.[1]||'',price:observed(priceText),seller:'Мега Крепеж',address:'ул. Галимджана Баруди, 18, Казань',phone:'+7 843 528-29-20'});});}
function novocraftOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<tr\b[^>]*class=["'][^"']*\bmain_item_wrapper\b[^"']*["'][^>]*>/gi).flatMap(block=>{const link=block.match(/<a\b[^>]*href=["']([^"']+)["'][^>]*class=["'][^"']*js-notice-block__title/i),priceTag=block.match(/<div\b[^>]*class=["'][^"']*\bprice\b[^"']*["'][^>]*data-currency=["']RUB["'][^>]*>/i)?.[0]||'',title=link?text(block.slice(link.index!,block.indexOf('</a>',link.index!)+4)):'';return hit(source,city,checkedAt,{title,link:link?.[1]||'',image:block.match(/<img\b[^>]*src=["']([^"']+)["']/i)?.[1]||'',price:observed(attr(priceTag,'data-value')),seller:'Novocraft',address:'ул. Аделя Кутуя, 181Ж, Казань',phone:'+7 843 236-97-10',availability:/item-stock[\s\S]{0,200}(?:Много|В наличии)/iu.test(block)?'in_stock':'unknown'});});}
function sksOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<li\b[^>]*class=["'][^"']*\bcolumn-33\b[^"']*["'][^>]*>/gi).flatMap(block=>{const link=block.match(/<a\b[^>]*href=["']([^"']+)["'][^>]*title=["']([^"']+)["']/i),priceText=block.match(/price_pruduct_on_cat[^>]*>\s*Цена:\s*([\d\s,.]+)\s*(?:руб|₽)/iu)?.[1]||'';return hit(source,city,checkedAt,{title:decode(link?.[2]||''),link:link?.[1]||'',image:block.match(/<img\b[^>]*src=["']([^"']+)["']/i)?.[1]||'',price:observed(priceText),seller:'СКС-Казань',phone:'+7 843 290-91-03',availability:/В наличии/iu.test(block)?'in_stock':'unknown'});});}
function autocraftOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<article\b[^>]*class=["'][^"']*\bproduct-card\b[^"']*["'][^>]*>/gi).flatMap(block=>{const link=block.match(/product-card__title[\s\S]*?<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i),priceText=block.match(/ecart-price[^>]*>\s*([\d\s,.]+)\s*руб/iu)?.[1]||'',image=block.match(/<img\b[^>]*src=["']([^"']+)["'][^>]*>/i)?.[1]||'';return hit(source,city,checkedAt,{title:text(link?.[2]||''),link:link?.[1]||'',image,price:observed(priceText),seller:'АвтоКрафт',category:'Автотовары',address:'ул. Аделя Кутуя, 72, Казань',phone:'+7 927 039-06-31',availability:/stock-in|Есть в наличии/iu.test(block)?'in_stock':'unknown'});});}
function gazzapOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<div\b[^>]*class=["'][^"']*\bms2_product\b[^"']*["'][^>]*>/gi).flatMap(block=>{const link=block.match(/cataloge__title[\s\S]*?<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i),href=link?.[1]||'',priceText=block.match(/\bdata-price=["']\s*([\d\s,.]+)["']/i)?.[1]||block.match(/\bc__price[^>]*>\s*([\d\s,.]+)</i)?.[1]||'',image=block.match(/<img\b[^>]*src=["']([^"']+)["'][^>]*>/i)?.[1]||'';return hit(source,city,checkedAt,{title:text(link?.[2]||''),link:href.startsWith('catalog/')?'/'+href:href,image,price:observed(priceText),seller:'ГАЗЗАПЧАСТИ',category:'Автотовары',address:'Мамадышский тракт, 35 к1, Казань',phone:'+7 843 267-42-52',availability:/В наличии/iu.test(block)?'in_stock':'unknown'});});}
function makpetsOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<li\b[^>]*class=["']\bproduct\s+type-product\b[^"']*["'][^>]*>/gi).flatMap(block=>{const link=block.match(/<h3\b[^>]*class=["'][^"']*\bproduct-title\b[^"']*["'][^>]*>\s*<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i),priceText=block.match(/<bdi>\s*([\d\s,.]+)(?:&nbsp;|\s)*</i)?.[1]||'',imageTag=block.match(/<img\b[^>]*>/i)?.[0]||'',image=attr(imageTag,'data-src')||attr(imageTag,'data-lazy')||attr(imageTag,'src');return hit(source,city,checkedAt,{title:text(link?.[2]||''),link:link?.[1]||'',image,price:observed(priceText),seller:'Makpets',category:'Зоотовары',address:'ул. Техническая, 17, Казань',phone:'+7 843 240-77-15',availability:/\binstock\b/iu.test(block)?'in_stock':'unknown'});});}
function biosferaOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<form\b[^>]*class=["'][^"']*\bproduct-preview\b[^"']*["'][^>]*>/gi).flatMap(block=>{const link=block.match(/product-preview__title[\s\S]*?<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i),priceText=block.match(/product-preview__price-cur[^>]*>\s*([\d\s,.]+)\s*(?:руб|₽)/iu)?.[1]||'',imageTag=[...block.matchAll(/<img\b[^>]*>/gi)].map(m=>m[0]).find(tag=>attr(tag,'itemprop')==='contentUrl')||'',image=attr(imageTag,'data-src')||attr(imageTag,'src');return hit(source,city,checkedAt,{title:text(link?.[2]||''),link:link?.[1]||'',image,price:observed(priceText),seller:'Биосфера',category:'Сад и дача',availability:/product-preview__available[\s\S]{0,100}В наличии/iu.test(block)?'in_stock':'unknown'});});}
function maikorcosOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<div\b[^>]*class=["'][^"']*\bm-product__card\b[^"']*["'][^>]*>/gi).flatMap(block=>{const productId=block.match(/handleProductCardClick\((\d+)/)?.[1],title=text(block.match(/<h2\b[^>]*class=["'][^"']*\bm-product-name\b[^"']*["'][^>]*>([\s\S]*?)<\/h2>/i)?.[1]||''),priceText=block.match(/m-product-price_actual[^>]*>\s*([\d\s,.]+)\s*руб/iu)?.[1]||'',rawImage=block.match(/<img\b[^>]*src=["']([^"']+)["']/i)?.[1]||'';return hit(source,city,checkedAt,{title,link:source+'#product-'+(productId||encodeURIComponent(title)),image:rawImage.startsWith('//')?'https:'+rawImage:rawImage,price:observed(priceText),seller:'MaiKorCos',category:'Красота и здоровье',address:'ул. Петербургская, 25, Казань',phone:'+7 967 363-13-68',availability:/m-product__out-of-stock/iu.test(block)?'out_of_stock':'in_stock'});});}
function koreaVisageOffers(html:string,source:string,city:string,checkedAt:string){return blocksFromStarts(html,/<div\b[^>]*class=["']widget["'][^>]*data-type=["']simple-image["'][^>]*>/gi,12).flatMap((block,index)=>{const paragraphs=[...block.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)].map(m=>text(m[1])).filter(Boolean),title=paragraphs.find(value=>!/^\d[\d\s]*\s*руб\.?$/iu.test(value))||'',priceText=paragraphs.find(value=>/^\d[\d\s]*\s*руб\.?$/iu.test(value))?.match(/[\d\s]+/)?.[0]||'',options=block.match(/<script\b[^>]*class=["']widget-options["'][^>]*>([\s\S]*?)<\/script>/i)?.[1]||'';let image='';try{const data=JSON.parse(options),base=String(data.storage||'').replace(/^\/\//,'https://');image=base+String(data.photoData?.name||'');}catch{}return title&&priceText?hit(source,city,checkedAt,{title,link:source+'#offer-'+index,image,price:observed(priceText),seller:'KOREA VISAGE',category:'Красота и здоровье'}):[];});}
