'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Check,ExternalLink,FileSpreadsheet,Globe,ImagePlus,Pencil,Plus,Send,Store,Trash2} from 'lucide-react';
import {ProductForm,ProductImport,UploadPhotos,type CatalogAction} from '@/app/catalog-app';
import {categories,money,type Product,type Shop} from '@/lib/model';
import './style.css';

type StoreInput={id?:string;name:string;category:(typeof categories)[number];city:string;street:string;phone:string;site:string;photos:string[]};
type DraftResponse={shop:Shop;products:Product[]};
const storageKey='ng_business_onboarding_v2';
const emptyStore:StoreInput={name:'',category:categories[0],city:'Казань',street:'',phone:'',site:'',photos:[]};

async function api(action:string,extra:Record<string,unknown>={}){const response=await fetch('/api/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})}),result=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String(result.error||'Не удалось сохранить данные'));return result;}
async function catalog(action:string,extra:Record<string,unknown>={}){const response=await fetch('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})}),result=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String(result.error||'Не удалось сохранить товар'));return result;}

export default function BusinessDemo(){
 const [step,setStep]=useState(1),[store,setStore]=useState<StoreInput>(emptyStore),[shop,setShop]=useState<Shop|null>(null),[products,setProducts]=useState<Product[]>([]),[editor,setEditor]=useState<'manual'|'photo'|'import'|'site'|null>(null),[editing,setEditing]=useState<Product|undefined>(),[catalogUrl,setCatalogUrl]=useState(''),[catalogConsent,setCatalogConsent]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[preview,setPreview]=useState(''),[submitted,setSubmitted]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null') as StoreInput|null;if(saved)setStore({...emptyStore,...saved});}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(store));}catch{}},[store]);
 async function refresh(id=store.id){if(!id)return;const response=await fetch(`/api/connect?draft=${encodeURIComponent(id)}`,{cache:'no-store'}),data=await response.json() as DraftResponse&{error?:string};if(!response.ok)throw new Error(data.error||'Не удалось открыть черновик');setShop(data.shop);setProducts(data.products);setStore(current=>({...current,id:data.shop.id,name:data.shop.name,category:(categories.includes(data.shop.category as typeof categories[number])?data.shop.category:categories[0]) as StoreInput['category'],city:data.shop.city,street:data.shop.street,phone:data.shop.phone,site:data.shop.site,photos:data.shop.photos}));}
 useEffect(()=>{if(store.id)void refresh(store.id).catch(()=>setStore(current=>({...current,id:undefined})));},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function saveStore(){setBusy(true);setNotice('');try{const result=await api('saveStore',{data:store}) as {id:string;shop:Shop};setStore(current=>({...current,id:result.id}));setShop(result.shop);setStep(2);setNotice('Черновик магазина сохранён на сервере.');}catch(error){setNotice((error as Error).message);}finally{setBusy(false)}}
 const productAction:CatalogAction=async(action,extra={})=>{const result=await catalog(action,extra);await refresh();if(action==='product'||action==='deleteProduct')setEditor(null);return result;};
 async function importSite(){if(!store.id)return;setBusy(true);setNotice('Проверяем структурированные данные на сайте…');try{const result=await api('catalogImport',{storeId:store.id,catalogUrl,catalogConsent});await refresh();setNotice(`Добавлено товаров: ${String(result.count||0)}. Цена и наличие без подтверждения останутся на проверке.`);setEditor(null);}catch(error){setNotice((error as Error).message);}finally{setBusy(false)}}
 async function openReview(){if(!store.id||!products.length){setNotice('Сначала добавьте хотя бы один товар.');return;}setBusy(true);try{const result=await api('preview',{storeId:store.id});setPreview(String(result.path||''));setStep(3);setEditor(null);}catch(error){setNotice((error as Error).message);}finally{setBusy(false)}}
 async function submit(){if(!store.id)return;setBusy(true);try{const result=await api('submitDraft',{storeId:store.id});setPreview(String(result.path||preview));setSubmitted(true);setNotice('Заявка отправлена. Магазин и товары уже сохранены и не потребуют повторного заполнения.');}catch(error){setNotice((error as Error).message);}finally{setBusy(false)}}
 const ready=useMemo(()=>products.filter(item=>item.name&&Number.isFinite(item.price)&&Number.isFinite(item.quantity)&&(item.photos?.length||item.sourceUrl||item.source)).length,[products]),needsReview=products.length-ready;
 const currentShop=shop||({...store,id:store.id||'draft',description:'',contact:store.phone,email:'',lat:0,lng:0,hours:'Уточнить часы работы',status:'reference',source:store.site,demo:false,visibility:'draft'} as Shop);
 return <main className="business-demo"><header><a className="business-back" href="/connect"><ArrowLeft size={18}/>Для бизнеса</a><a className="business-logo" href="/">Найди<span>Go</span></a><span>Черновик · не виден покупателям</span></header><section className="business-demo-intro"><p>СОЗДАНИЕ МАГАЗИНА · 3 ШАГА</p><h1>Добавьте магазин в НайдиGo</h1><p>Укажите основные данные, загрузите товары удобным способом и посмотрите будущую витрину до отправки. Черновик сохраняется на сервере.</p></section><div className="business-onboarding-steps">{['Магазин','Товары','Проверка'].map((label,index)=><button key={label} className={step===index+1?'active':step>index+1?'done':''} onClick={()=>index+1<step&&setStep(index+1)}><span>{step>index+1?<Check size={16}/>:index+1}</span><small>Шаг {index+1}</small>{label}</button>)}</div>
 {step===1&&<section className="business-demo-form business-step">
  <h2>1. Магазин</h2><p className="business-help">Только основные данные. Описание, часы работы и дополнительные контакты можно заполнить позже.</p>
  <label>Название<input required value={store.name} maxLength={200} onChange={e=>setStore(current=>({...current,name:e.target.value}))}/></label>
  <div className="business-demo-grid"><label>Город<input required value={store.city} maxLength={100} onChange={e=>setStore(current=>({...current,city:e.target.value}))}/></label><label>Адрес<input required value={store.street} maxLength={300} onChange={e=>setStore(current=>({...current,street:e.target.value}))}/></label></div>
  <div className="business-demo-grid"><label>Телефон<input required value={store.phone} maxLength={100} onChange={e=>setStore(current=>({...current,phone:e.target.value}))}/></label><label>Сайт<input type="url" value={store.site} placeholder="https://…" onChange={e=>setStore(current=>({...current,site:e.target.value}))}/></label></div>
  <label>Основная категория<select value={store.category} onChange={e=>setStore(current=>({...current,category:e.target.value as StoreInput['category']}))}>{categories.map(category=><option key={category}>{category}</option>)}</select></label>
  <div><b>Логотип или фото</b><UploadPhotos endpoint="/api/catalog" value={store.photos} onChange={photos=>setStore(current=>({...current,photos}))}/></div>
  <div className="business-actions"><button className="d-btn" disabled={busy||store.name.trim().length<2||store.phone.trim().length<5||!store.street.trim()} onClick={()=>void saveStore()}>{busy?'Сохраняем…':'Продолжить к товарам'}</button></div>
 </section>}
 {step===2&&<section className="business-step"><div className="business-step-title"><div><h2>2. Товары</h2><p className="business-help">Выберите удобный способ. Все способы добавляют товары в этот же черновик.</p></div><button className="d-btn" disabled={!products.length||busy} onClick={()=>void openReview()}>Перейти к проверке</button></div><div className="business-product-methods"><button onClick={()=>setEditor('site')}><Globe/><b>Загрузить с сайта</b><span>Собрать карточки со структурированной страницы</span></button><button onClick={()=>setEditor('import')}><FileSpreadsheet/><b>Excel / CSV</b><span>Сопоставить колонки и проверить перед импортом</span></button><button onClick={()=>{setEditing(undefined);setEditor('photo')}}><ImagePlus/><b>Добавить по фото</b><span>AI заполнит черновик, но не цену и остаток</span></button><button onClick={()=>{setEditing(undefined);setEditor('manual')}}><Plus/><b>Добавить вручную</b><span>Обычная форма товара из кабинета</span></button></div>
 {editor==='site'&&<div className="d-panel business-editor"><h3>Собрать товары с сайта</h3><label>Страница каталога<input type="url" placeholder="https://магазин.рф/catalog" value={catalogUrl} onChange={e=>setCatalogUrl(e.target.value)}/></label><label className="ng-checkbox"><input type="checkbox" checked={catalogConsent} onChange={e=>setCatalogConsent(e.target.checked)}/>Я управляю этим сайтом и разрешаю проверить публичные товарные данные</label><button className="d-btn" disabled={busy||!catalogConsent||!catalogUrl} onClick={()=>void importSite()}>{busy?'Проверяем…':'Найти товары на странице'}</button></div>}
 {editor==='import'&&<ProductImport shop={currentShop} action={productAction}/>}
 {(editor==='manual'||editor==='photo')&&<div className="business-editor"><ProductForm key={editing?.id||editor} initial={editing} shop={currentShop} action={productAction}/></div>}
 <div className="business-product-list"><div className="business-step-title"><h3>Товары · {products.length}</h3>{products.length>0&&<span>{ready} готово · {needsReview} требуют проверки</span>}</div>{!products.length&&<div className="business-empty"><Store/><b>Товаров пока нет</b><span>Добавьте первый товар одним из четырёх способов выше.</span></div>}{products.map(item=><article key={item.id}><img src={item.photos?.[0]||'/brand/product-placeholder.svg'} alt=""/><div><b>{item.name}</b><span>{item.category} · {item.sourceType==='catalog'?'С сайта':item.sourceType==='csv'||item.sourceType==='xlsx'?'Импорт':'Вручную'}</span></div><strong>{item.price===null?'Цена не указана':money(item.price)}</strong><span>{item.quantity===null?'Остаток проверить':item.stockConfirmed===false?'Остаток не подтверждён':`${item.quantity} шт.`}</span><em className={item.published?'ready':'review'}>{item.published?'Готов к публикации':'Требует проверки'}</em><button aria-label="Редактировать" onClick={()=>{setEditing(item);setEditor('manual')}}><Pencil size={17}/></button><button aria-label="Удалить" onClick={()=>void productAction('deleteProduct',{id:item.id})}><Trash2 size={17}/></button></article>)}</div></section>}
 {step===3&&<section className="business-step"><div className="business-step-title"><div><h2>3. Проверка</h2><p className="business-help">Это тот же магазин и те же товары, которые администратор проверит и опубликует.</p></div><button className="d-btn secondary" onClick={()=>setStep(2)}>Исправить товары</button></div><div className="business-review"><article><div className="business-review-cover">{store.photos[0]?<img src={store.photos[0]} alt=""/>:<Store/>}</div><h3>{store.name}</h3><p>{store.city}, {store.street}</p><p>{store.phone}{store.site&&<> · <a href={store.site} target="_blank" rel="noreferrer">сайт</a></>}</p></article><article><h3>Готовность каталога</h3><strong>{products.length}</strong><p>товаров добавлено</p><div><span><Check/>Готовы: {ready}</span><span>Нужно проверить: {needsReview}</span></div></article></div><div className="business-product-list review-list">{products.map(item=><article key={item.id}><img src={item.photos?.[0]||'/brand/product-placeholder.svg'} alt=""/><div><b>{item.name}</b><span>{item.category}</span></div><strong>{item.price===null?'Уточнить цену':money(item.price)}</strong><span>{item.quantity===null?'Остаток не указан':`${item.quantity} шт.`}</span></article>)}</div><div className="business-actions"><a className="d-btn secondary" href={preview||'#'} target="_blank" aria-disabled={!preview}><ExternalLink size={17}/>Посмотреть как покупатель</a><button className="d-btn" disabled={busy||submitted} onClick={()=>void submit()}><Send size={17}/>{submitted?'Заявка отправлена':'Отправить на подключение'}</button></div>{submitted&&<div className="business-success"><Check/><div><b>Заявка принята</b><p>После проверки администратор публикует этот же магазин и создаёт персональное приглашение владельцу. Повторно заполнять товары не нужно.</p></div></div>}</section>}
 {notice&&<p className="business-demo-notice" role="status">{notice}</p>}</main>;
}
