import {z} from 'zod';
import {env} from 'cloudflare:workers';
import {db,bucket} from '@/db';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {requestOrigin} from '@/lib/onboarding';
import {seedShops,seedProducts} from '@/lib/seed';
import {rankSearch} from '@/lib/search';
import {type Shop,type Product,type Inquiry} from '@/lib/model';
export const dynamic='force-dynamic';
const text=z.string().trim().max(4000),short=z.string().trim().min(1).max(200);
const socialUrl=z.union([z.literal(''),z.string().url().regex(/^https?:\/\//)]).optional();
const photos=z.array(z.string().max(1000)).max(5);
const shopSchema=z.object({addressConfirmed:z.boolean().default(false),name:short,category:short,description:text,contact:short,phone:short,email:z.string().email().max(200),city:short,street:short,lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180),hours:short,vk:socialUrl,telegram:socialUrl,max:socialUrl,site:z.union([z.literal(''),z.string().url().regex(/^https?:\/\//)]),photos});
const productSchema=z.object({storeId:short,name:short,category:short,brand:text,model:text,description:text,features:text,price:z.number().min(0).max(1e9),quantity:z.number().int().min(0).max(1e7),sku:text,published:z.boolean(),photos,keywords:text,stockConfirmed:z.boolean().default(true)});
type Row={id:string;data:string;owner?:string|null;customer?:string;applicant?:string;status?:string;store_id:string;visibility?:'draft'|'public'};
const parse=<T,>(r:Row)=>JSON.parse(r.data) as T;
const fail=(message:string,status=400)=>Response.json({error:message},{status});
async function identity(req:Request){const user=await getChatGPTUser();const old=req.headers.get('cookie')?.match(/(?:^|;\s*)ng_guest=([a-f0-9-]{36})/)?.[1];const guest=old||crypto.randomUUID();return {user,key:user?.userId||`guest:${guest}`,cookie:old?null:`ng_guest=${guest}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${new URL(req.url).protocol==='https:'?'; Secure':''}`,admin:!!user&&!!env.ADMIN_EMAIL&&user.email.toLowerCase()===env.ADMIN_EMAIL.toLowerCase()};}
async function seed(force=false){const d=db();if(!force&&await d.prepare("SELECT id FROM shops WHERE id='demo-s0'").first())return;await d.batch([...seedShops.map(s=>d.prepare('INSERT OR IGNORE INTO shops (id,owner,data) VALUES (?,NULL,?)').bind(s.id,JSON.stringify(s))),...seedProducts.map(p=>d.prepare('INSERT OR IGNORE INTO products (id,store_id,published,data) VALUES (?,?,1,?)').bind(p.id,p.storeId,JSON.stringify(p)))]);}
async function own(id:string,key:string){const row=await db().prepare('SELECT * FROM shops WHERE id=? AND owner=?').bind(id,key).first<Row>();if(!row)throw new Error('Нет доступа к этому магазину');return parse<Shop>(row);}
async function checkPhotos(urls:string[],owner:string,existing:string[]=[]){for(const url of urls){if(existing.includes(url))continue;if(!/^\/api\/photos\/[a-f0-9-]{36}$/.test(url))throw new Error('Загрузите фотографию через форму');const row=await db().prepare('SELECT id FROM uploads WHERE id=? AND owner=?').bind(url.split('/').pop(),owner).first();if(!row)throw new Error('Фотография не найдена или принадлежит другому владельцу');}}
export async function GET(req:Request){try{const who=await identity(req),d=db();const rows=await d.prepare("SELECT * FROM shops WHERE (visibility='public' AND COALESCE(json_extract(data,'$.demo'),0)=0) OR owner=?").bind(who.key).all<Row>();const stores=rows.results.map(r=>{const s=parse<Shop>(r) as Shop&{notes?:string};if(r.owner!==who.key){delete s.notes;s.contact='';}return {...s,visibility:r.visibility}}),owned=rows.results.filter(s=>s.owner===who.key).map(s=>s.id);const p=await d.prepare('SELECT p.* FROM products p JOIN shops s ON p.store_id=s.id WHERE (p.published=1 AND s.visibility=\'public\' AND COALESCE(json_extract(p.data,\'$.demo\'),0)=0 AND COALESCE(json_extract(s.data,\'$.demo\'),0)=0) OR s.owner=?').bind(who.key).all<Row>();const messages=await d.prepare('SELECT i.* FROM inquiries i JOIN shops s ON i.store_id=s.id WHERE i.customer=? OR s.owner=? ORDER BY i.rowid DESC').bind(who.key,who.key).all<Row>();const claims=await d.prepare(who.admin?'SELECT * FROM claims ORDER BY rowid DESC':'SELECT * FROM claims WHERE applicant=? ORDER BY rowid DESC').bind(...(who.admin?[]:[who.key])).all<Row>();const fav=await d.prepare('SELECT product_id FROM favorites WHERE customer=?').bind(who.key).all<{product_id:string}>();return Response.json({stores,products:p.results.map(parse<Product>),owned,inquiries:messages.results.map(parse<Inquiry>),claims:claims.results.map(r=>({...parse<object>(r),status:r.status})),favorites:fav.results.map(f=>f.product_id),signedIn:!!who.user,admin:who.admin},{headers:{'Cache-Control':'no-store',...(who.cookie?{'Set-Cookie':who.cookie}:{})}});}catch(e){console.error(e);return fail('Не удалось загрузить каталог. Попробуйте ещё раз.',503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==requestOrigin(req))return fail('Недопустимый источник запроса',403);const who=await identity(req),d=db();const body=await req.json() as Record<string,unknown>;const action=String(body.action);const id=typeof body.id==='string'?body.id:'';let result:unknown={ok:true};
if(action==='search'){const query=z.string().trim().max(200).parse(body.query);const rows=await d.prepare("SELECT p.* FROM products p JOIN shops s ON s.id=p.store_id WHERE p.published=1 AND s.visibility='public' AND COALESCE(json_extract(p.data,'$.demo'),0)=0 AND COALESCE(json_extract(s.data,'$.demo'),0)=0").all<Row>();const products=rankSearch(rows.results.map(parse<Product>),query);await d.prepare('INSERT INTO searches (id,query,result_count,created_at) VALUES (?,?,?,?)').bind(crypto.randomUUID(),query,products.length,new Date().toISOString()).run();result={products};}
else if(action==='favorite'){const product=await d.prepare("SELECT p.id FROM products p JOIN shops s ON s.id=p.store_id WHERE p.id=? AND p.published=1 AND s.visibility='public' AND COALESCE(json_extract(p.data,'$.demo'),0)=0 AND COALESCE(json_extract(s.data,'$.demo'),0)=0").bind(id).first();if(!product)return fail('Товар не найден',404);if(body.remove)await d.prepare('DELETE FROM favorites WHERE customer=? AND product_id=?').bind(who.key,id).run();else await d.prepare('INSERT OR IGNORE INTO favorites (customer,product_id) VALUES (?,?)').bind(who.key,id).run();}
else if(action==='inquiry'){const question=short.parse(body.question);const row=await d.prepare("SELECT p.* FROM products p JOIN shops s ON s.id=p.store_id WHERE p.id=? AND p.published=1 AND s.visibility='public' AND COALESCE(json_extract(p.data,'$.demo'),0)=0 AND COALESCE(json_extract(s.data,'$.demo'),0)=0").bind(id).first<Row>();if(!row)return fail('Товар не найден',404);const p=parse<Product>(row);const sr=await d.prepare('SELECT * FROM shops WHERE id=?').bind(p.storeId).first<Row>();if(!sr||parse<Shop>(sr).status!=='connected')return fail('Магазин ещё не подключён');const message:Inquiry={id:crypto.randomUUID(),storeId:p.storeId,productId:p.id,productName:p.name,question,answer:null,createdAt:new Date().toISOString(),demo:p.demo};await d.prepare('INSERT INTO inquiries (id,store_id,customer,data) VALUES (?,?,?,?)').bind(message.id,p.storeId,who.key,JSON.stringify(message)).run();}
else {if(!who.user)return fail('Войдите, чтобы управлять магазином',401);
if(action==='shop'){const input=shopSchema.parse(body.data);const previous=id?await own(id,who.key):undefined;await checkPhotos(input.photos,who.key,previous?.photos);const shop:Shop={...previous,...input,id:id||crypto.randomUUID(),status:'connected',source:'Данные предоставлены владельцем',demo:previous?.demo||false};if(id)await d.prepare('UPDATE shops SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(shop),id,who.key).run();else await d.prepare('INSERT INTO shops (id,owner,data) VALUES (?,?,?)').bind(shop.id,who.key,JSON.stringify(shop)).run();result={id:shop.id};}
else if(action==='product'){const input=productSchema.parse(body.data);await own(input.storeId,who.key);let previous:Product|undefined;if(id){const row=await d.prepare('SELECT * FROM products WHERE id=? AND store_id=?').bind(id,input.storeId).first<Row>();if(!row)return fail('Товар не найден',404);previous=parse<Product>(row);}await checkPhotos(input.photos,who.key,previous?.photos);if(input.published&&!input.photos.length&&!previous?.source)return fail('Добавьте фотографию для публикации');const product:Product={...previous,...input,id:id||crypto.randomUUID(),demo:previous?.demo||false};if(id)await d.prepare('UPDATE products SET published=?,data=? WHERE id=? AND store_id=?').bind(+input.published,JSON.stringify(product),id,input.storeId).run();else await d.prepare('INSERT INTO products (id,store_id,published,data) VALUES (?,?,?,?)').bind(product.id,input.storeId,+input.published,JSON.stringify(product)).run();result={id:product.id};}
else if(action==='deleteProduct'){const row=await d.prepare('SELECT * FROM products WHERE id=?').bind(id).first<Row>();if(!row)return fail('Товар не найден',404);await own(parse<Product>(row).storeId,who.key);await d.batch([d.prepare('DELETE FROM favorites WHERE product_id=?').bind(id),d.prepare('DELETE FROM products WHERE id=?').bind(id)]);}
else if(action==='reply'){const row=await d.prepare('SELECT * FROM inquiries WHERE id=?').bind(id).first<Row>();if(!row)return fail('Обращение не найдено',404);const message=parse<Inquiry>(row);await own(message.storeId,who.key);message.answer=short.parse(body.answer);await d.prepare('UPDATE inquiries SET data=? WHERE id=?').bind(JSON.stringify(message),id).run();}
else if(action==='claim'){const row=await d.prepare("SELECT * FROM shops WHERE id=? AND visibility='public' AND id NOT IN (SELECT store_id FROM onboarding)").bind(id).first<Row>();if(!row||row.owner||parse<Shop>(row).status!=='reference')return fail('Карточка недоступна для заявки');const duplicate=await d.prepare("SELECT id FROM claims WHERE store_id=? AND applicant=? AND status='pending'").bind(id,who.key).first();if(duplicate)return fail('Ваша заявка уже ожидает проверки');const claim={id:crypto.randomUUID(),storeId:id,contact:short.parse(body.contact),message:short.parse(body.message),createdAt:new Date().toISOString()};await d.prepare('INSERT INTO claims (id,store_id,applicant,status,data) VALUES (?,?,?,?,?)').bind(claim.id,id,who.key,'pending',JSON.stringify(claim)).run();}
else if(action==='approve'||action==='reject'){if(!who.admin)return fail('Только администратор может проверять заявки',403);const row=await d.prepare("SELECT * FROM claims WHERE id=? AND status='pending'").bind(id).first<Row>();if(!row)return fail('Заявка уже обработана',409);if(action==='reject')await d.prepare("UPDATE claims SET status='rejected' WHERE id=?").bind(id).run();else {const sr=await d.prepare("SELECT * FROM shops WHERE id=? AND visibility='public' AND id NOT IN (SELECT store_id FROM onboarding)").bind(row.store_id).first<Row>();if(!sr||sr.owner)return fail('Магазин уже подключён',409);const shop={...parse<Shop>(sr),status:'connected'};await d.batch([d.prepare('UPDATE shops SET owner=?,data=? WHERE id=? AND owner IS NULL').bind(row.applicant,JSON.stringify(shop),row.store_id),d.prepare("UPDATE claims SET status=CASE WHEN id=? THEN 'approved' ELSE 'rejected' END WHERE store_id=? AND status='pending'").bind(id,row.store_id)]);}}
else if(action==='resetDemo'){if(!who.admin)return fail('Сброс доступен администратору',403);await d.batch([d.prepare("DELETE FROM inquiries WHERE store_id LIKE 'demo-s%'"),d.prepare("DELETE FROM claims WHERE store_id LIKE 'demo-s%'"),d.prepare("DELETE FROM favorites WHERE product_id LIKE 'demo-p%'"),d.prepare("DELETE FROM products WHERE id LIKE 'demo-p%'"),d.prepare("UPDATE shops SET owner=NULL WHERE id LIKE 'demo-s%'")]);for(const s of seedShops)await d.prepare('UPDATE shops SET data=? WHERE id=?').bind(JSON.stringify(s),s.id).run();await seed(true);}
else return fail('Неизвестное действие');}
return Response.json(result,{headers:who.cookie?{'Set-Cookie':who.cookie}:{}});
}catch(e){console.error(e);if(e instanceof z.ZodError)return fail('Проверьте поля формы: '+e.issues.map(i=>i.path.join('.')).join(', '));return fail(e instanceof Error?e.message:'Не удалось сохранить данные',400);}}
export async function PUT(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==requestOrigin(req))return fail('Недопустимый источник',403);const who=await identity(req);if(!who.user)return fail('Войдите для загрузки фотографий',401);if(Number(req.headers.get('content-length')||0)>5*1024*1024)return fail('Файл должен быть меньше 5 МБ');const mime=req.headers.get('content-type')||'';if(!['image/jpeg','image/png','image/webp'].includes(mime))return fail('Используйте JPG, PNG или WebP');const bytes=new Uint8Array(await req.arrayBuffer());if(!bytes.length||bytes.length>5*1024*1024)return fail('Файл должен быть от 1 байта до 5 МБ');const valid=mime==='image/jpeg'?bytes[0]===255&&bytes[1]===216:mime==='image/png'?bytes[0]===137&&bytes[1]===80:bytes[0]===82&&bytes[1]===73&&bytes[8]===87&&bytes[9]===69;if(!valid)return fail('Содержимое не соответствует формату изображения');const id=crypto.randomUUID();await bucket().put(id,bytes,{httpMetadata:{contentType:mime}});await db().prepare('INSERT INTO uploads (id,owner,mime) VALUES (?,?,?)').bind(id,who.key,mime).run();return Response.json({url:`/api/photos/${id}`});}catch(e){console.error(e);return fail('Не удалось загрузить фотографию',503);}}
