import {z} from 'zod';
import {db} from '@/db';
import {actor,draftSchema,importedProduct,token,hash,privateHeaders,sameOrigin,checkUploadOwnership} from '@/lib/onboarding';
export const dynamic='force-dynamic';
type Row={id:string;data:string;visibility:string;owner:string|null};
export async function GET(){const a=await actor();if(!a.admin)return Response.json({error:'Требуются права администратора'},{status:403,headers:privateHeaders});const shops=await db().prepare('SELECT s.*,count(p.id) AS productCount FROM shops s LEFT JOIN products p ON s.id=p.store_id WHERE s.id IN (SELECT store_id FROM onboarding) GROUP BY s.id ORDER BY s.rowid DESC').all<Row&{productCount:number}>();const products=await db().prepare('SELECT p.* FROM products p JOIN onboarding o ON p.store_id=o.store_id').all<{data:string}>();return Response.json({shops:shops.results.map(r=>({...JSON.parse(r.data),visibility:r.visibility,hasOwner:!!r.owner,productCount:r.productCount})),products:products.results.map(r=>JSON.parse(r.data))},{headers:privateHeaders});}
export async function POST(req:Request){try{const payload=await req.json();sameOrigin(req);const a=await actor();if(!a.admin||!a.user)return Response.json({error:'Требуются права администратора'},{status:403});const body=payload as {action:string;id?:string;data:unknown;consent?:string;email?:string};const d=db(),now=new Date().toISOString();let result:unknown={ok:true};
if(body.action==='save'){const input=draftSchema.parse(body.data);await checkUploadOwnership(input.photos,a.user.userId);const id=body.id||crypto.randomUUID();if(body.id){const old=await d.prepare('SELECT s.* FROM shops s JOIN onboarding o ON o.store_id=s.id WHERE s.id=?').bind(id).first<Row>();if(!old)throw new Error('Черновик не найден');if(old.visibility!=='draft'||old.owner)throw new Error('Опубликованная витрина недоступна для редактирования черновика');}const data={...input,id,status:'reference',demo:false,personalDemo:true,ownerConfirmed:false};if(body.id)await d.prepare('UPDATE shops SET data=? WHERE id=? AND visibility=?').bind(JSON.stringify(data),id,'draft').run();else await d.batch([d.prepare("INSERT INTO shops (id,owner,data,visibility) VALUES (?,NULL,?,'draft')").bind(id,JSON.stringify(data)),d.prepare('INSERT INTO onboarding (store_id,created_by,created_at) VALUES (?,?,?)').bind(id,a.user.userId,now)]);result={id};}
else {const id=z.string().min(1).parse(body.id);const row=await d.prepare('SELECT s.* FROM shops s JOIN onboarding o ON o.store_id=s.id WHERE s.id=?').bind(id).first<Row>();if(!row)throw new Error('Витрина не найдена');
if(body.action==='product'){if(row.visibility!=='draft'||row.owner)throw new Error('Сначала снимите витрину с публикации');const p=importedProduct.parse(body.data);await checkUploadOwnership(p.photos,a.user.userId);if(p.photos.length&&!p.imagePermission.trim())throw new Error('Укажите основание использования фотографий');const pid=p.id||crypto.randomUUID(),data={...p,id:pid,storeId:id,published:false,demo:p.testOnly};if(p.id){const exists=await d.prepare('SELECT id FROM products WHERE id=? AND store_id=?').bind(pid,id).first();if(!exists)throw new Error('Товар не найден');await d.prepare('UPDATE products SET data=?,published=0 WHERE id=? AND store_id=?').bind(JSON.stringify(data),pid,id).run();}if(!p.id)await d.prepare('INSERT INTO products (id,store_id,published,data) VALUES (?,?,0,?)').bind(pid,id,JSON.stringify(data)).run();result={id:pid};}
else if(body.action==='deleteProduct'){if(row.visibility!=='draft')throw new Error('Товар опубликован');const productId=z.string().parse(body.data);await d.prepare('DELETE FROM products WHERE id=? AND store_id=?').bind(productId,id).run();}
else if(body.action==='preview'){const raw=token(),expires=new Date(Date.now()+30*864e5).toISOString();await d.batch([d.prepare('UPDATE preview_tokens SET revoked=1 WHERE store_id=?').bind(id),d.prepare('INSERT INTO preview_tokens (hash,store_id,expires_at,revoked) VALUES (?,?,?,0)').bind(await hash(raw),id,expires)]);result={path:`/preview/${raw}`,expiresAt:expires};}
else if(body.action==='revokePreview'){await d.prepare('UPDATE preview_tokens SET revoked=1 WHERE store_id=?').bind(id).run();}
else if(body.action==='publish'){if(row.owner)throw new Error('Управление уже передано владельцу');const consent=z.string().trim().min(10).max(2000).parse(body.consent);const s=JSON.parse(row.data);if(!s.phone||!s.street||!s.source||s.lat===null||s.lng===null)throw new Error('Проверьте телефон, адрес, координаты и источник');const rows=await d.prepare('SELECT * FROM products WHERE store_id=?').bind(id).all<{id:string;data:string}>();if(!rows.results.length)throw new Error('Добавьте товары');const items=rows.results.map(r=>JSON.parse(r.data));if(items.some(p=>p.testOnly||p.demo))throw new Error('Тестовые товары нельзя публиковать');await d.batch([d.prepare("UPDATE shops SET visibility='public',data=? WHERE id=?").bind(JSON.stringify({...s,ownerConfirmed:true,personalDemo:false,confirmedAt:now,status:'reference'}),id),d.prepare('UPDATE onboarding SET consent=?,confirmed_at=? WHERE store_id=?').bind(consent,now,id),...items.map(p=>d.prepare('UPDATE products SET published=1,data=? WHERE id=? AND store_id=?').bind(JSON.stringify({...p,published:true}),p.id,id))]);}
else if(body.action==='unpublish'){await d.prepare("UPDATE shops SET visibility='draft' WHERE id=?").bind(id).run();}
else if(body.action==='invite'){if(row.visibility!=='public'||!JSON.parse(row.data).ownerConfirmed||row.owner)throw new Error('Сначала согласуйте и опубликуйте витрину');const email=z.string().email().parse(body.email).toLowerCase();const raw=token(),expires=new Date(Date.now()+7*864e5).toISOString();await d.batch([d.prepare('UPDATE owner_invites SET used_at=? WHERE store_id=? AND used_at IS NULL').bind(now,id),d.prepare('INSERT INTO owner_invites (hash,store_id,email,expires_at) VALUES (?,?,?,?)').bind(await hash(raw),id,email,expires)]);result={path:`/invite/${raw}`,email,expiresAt:expires};}
else throw new Error('Неизвестное действие');}
return Response.json(result,{headers:privateHeaders});}catch(e){return Response.json({error:e instanceof z.ZodError?e.issues.map(i=>i.path.join('.')+': '+i.message).join('; '):(e as Error).message},{status:400,headers:privateHeaders});}}
