'use client';
import {useMemo,useState} from 'react';
import {Clock3,ExternalLink,MapPin,Navigation,Phone,Search,ShieldCheck,Store} from 'lucide-react';

const products=[
 {name:'Аккумуляторная дрель 16 В',price:'7 490 ₽',stock:'В наличии',category:'Электроинструмент',art:'tool-one'},
 {name:'Дрель-шуруповёрт 20 В',price:'14 990 ₽',stock:'В наличии',category:'Электроинструмент',art:'tool-two'},
 {name:'Аккумуляторный гайковёрт',price:'6 160 ₽',stock:'Осталось 2 шт.',category:'Ручной инструмент',art:'tool-three'},
];

export default function DemoStorePreview({compact=false}:{compact?:boolean}){const [query,setQuery]=useState(''),filtered=useMemo(()=>products.filter(item=>(item.name+' '+item.category).toLowerCase().includes(query.toLowerCase())),[query]);return <section className={'connect-store-preview '+(compact?'compact':'full')} aria-label="Демонстрация страницы магазина"><div className="connect-store-cover"><img src="/categories/home-repair.webp" alt="Демонстрационная обложка магазина инструментов"/><div className="connect-store-logo"><Store/></div></div><div className="connect-store-head"><div><span><ShieldCheck/>Демонстрационный магазин</span><h2>Мастер инструмента</h2><p>Строительный инструмент и расходные материалы</p></div></div><div className="connect-store-meta"><span><MapPin/>Казань, ул. Габдуллы Тукая, 115</span><span><Clock3/>Ежедневно, 09:00–20:00</span></div><div className="connect-store-buttons"><button type="button"><Phone/>Позвонить</button><button type="button"><Navigation/>Маршрут</button><button type="button"><ExternalLink/>Сайт</button></div>{!compact&&<><label className="connect-store-search"><Search/><input aria-label="Поиск по товарам демо-магазина" placeholder="Поиск по товарам магазина" value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="connect-store-tabs"><b>Все товары</b><span>Электроинструмент</span><span>Расходные материалы</span><span>Крепёж</span></div></>}<div className="connect-demo-products">{(compact?products:filtered).map(item=><article key={item.name}><div className={'connect-demo-tool '+item.art} role="img" aria-label={item.name}/><small>{item.category}</small><b>{item.name}</b><strong>{item.price}</strong><span>{item.stock}</span></article>)}</div>{!compact&&!filtered.length&&<p className="connect-demo-empty">В демо-каталоге нет такого товара.</p>}<p className="connect-demo-disclaimer">Демонстрация интерфейса: магазин, цены и наличие показаны только как пример оформления.</p></section>}
