import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const database=new DatabaseSync(':memory:');database.exec(await readFile('drizzle/0004_acoustic_stepford_cuckoos.sql','utf8'));
const wrap=(sql,args=[])=>({bind:(...values)=>wrap(sql,values),first:async()=>database.prepare(sql).get(...args)||null,run:async()=>({meta:{changes:database.prepare(sql).run(...args).changes}})});
globalThis.budgetTestDB={prepare:sql=>wrap(sql),batch:async statements=>{database.exec('BEGIN');try{const rows=[];for(const s of statements)rows.push(await s.run());database.exec('COMMIT');return rows;}catch(e){database.exec('ROLLBACK');throw e;}}};
let source=await readFile('lib/api-budget.ts','utf8');source=source.replace("import {recordUsage,currentUsage} from './search-usage';","const recordUsage=()=>{};const currentUsage=()=>undefined;").replace("import {env} from 'cloudflare:workers';","const env={API_MONTHLY_LIMIT_RUB:'3000',API_MAX_CALL_RUB:'20'};").replace("import {db} from '@/db';","const db=()=>globalThis.budgetTestDB;");
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {reserveCall,finishCall,budgetState,configuredLimitKopecks}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
assert.equal(configuredLimitKopecks('15000'),1500000);assert.equal(configuredLimitKopecks('0'),0);assert.equal(configuredLimitKopecks('invalid'),0);assert.equal(configuredLimitKopecks('-1'),0);assert.equal(configuredLimitKopecks(undefined),300000);
const c=await reserveCall('test','model');assert.equal((await budgetState()).committedRub,20);await assert.rejects(reserveCall('test','model'));
await finishCall(c,'complete',.123,{tokens:10});assert.equal((await budgetState()).committedRub,.13);
await finishCall(c,'complete',.123,{});assert.equal((await budgetState()).committedRub,.13,'idempotent settlement');
for(const [sum,threshold] of [[150000,50],[240000,80],[300000,100]]){database.prepare('UPDATE api_budget SET committed=?').run(sum);assert.equal((await budgetState()).warning,threshold);}
await assert.rejects(reserveCall('test','model'),'monthly stop');database.prepare('UPDATE api_budget SET committed=299000').run();await assert.rejects(reserveCall('test','model'),'reservation cannot cross limit');
database.prepare('UPDATE api_budget SET committed=0').run();const unknown=await reserveCall('test','model');await finishCall(unknown,'unknown',null,{});assert.equal((await budgetState()).committedRub,20);
const next=await reserveCall('test','model');await finishCall(next,'complete',.1,{});assert.equal((await budgetState()).committedRub,20.1,'old unknown reserve retained');assert.equal(database.prepare('SELECT status FROM api_calls WHERE id=?').get(unknown.id).status,'unknown');
const second=await reserveCall('test','model');await finishCall(second,'unknown',null,{});const third=await reserveCall('test','model');await finishCall(third,'unknown',null,{});await assert.rejects(reserveCall('test','model'),'uncertainty cap stops repeated unknown costs');
database.prepare("UPDATE api_calls SET status='complete' WHERE id=?").run(third.id);const stale=await reserveCall('test','model');database.prepare('UPDATE api_calls SET created_at=? WHERE id=?').run(Date.now()-180000,stale.id);await assert.rejects(reserveCall('test','model'),'stale pending counts toward uncertainty cap');
console.log('PASS: durable reservations, single in-flight call, idempotent settlement, budget thresholds, monthly stop, bounded unknown billing, original unknown preserved, stale pending capped. In-memory test only.');database.close();
