'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera} from 'lucide-react';
export default function PhotoSearch({onQuery}:{onQuery:(query:string)=>void}){
 const [photo,setPhoto]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const version=useRef(0);
 useEffect(()=>()=>{version.current++;},[]);
 async function choose(file?:File){const n=++version.current;setPhoto('');setMessage('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setMessage('Выберите JPG, PNG или WebP до 10 МБ.');return;}
 try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',.8);if(data.length>1500000)throw Error();if(n===version.current)setPhoto(data);}catch{setMessage('Не удалось прочитать фото. Попробуйте другое или опишите предмет.');}}
 async function recognize(){setBusy(true);setMessage('Распознаём предмет…');try{const r=await fetch('/api/search-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:photo,consent:true})}),b=await r.json() as {error?:string;query:string;question?:string};if(!r.ok)throw Error(b.error||'Поиск по фото недоступен');setPhoto('');setMessage('Ищем похожие предметы: '+b.query+(b.question?' · '+b.question:''));onQuery(b.query);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="finder-photo"><label><Camera size={18}/> Найти по фото<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void choose(e.target.files?.[0]);e.target.value='';}}/></label>{photo&&<div><img src={photo} alt="Выбранный предмет" style={{width:100,height:100,objectFit:'contain'}}/><p>Для распознавания фото будет отправлено в RouterAI. На нашем сервере оно не сохраняется.</p><button disabled={busy} onClick={()=>void recognize()}>Распознать и найти похожее</button><button disabled={busy} onClick={()=>setPhoto('')}>Удалить фото</button></div>}{message&&<p role="status" className="finder-note">{message}</p>}</div>;
}
