'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Search,MapPin,Wrench,Car,Bike,Monitor,Flower2,PawPrint} from 'lucide-react';
import {categories,type Product,type Shop} from '@/lib/model';
import {parseIntent,hitShop} from '@/lib/city-search';
import type {SearchResponse} from '@/lib/search-engine';
import {resolveSearch,type SearchContext} from '@/lib/search-context';
import PhotoSearch from './photo-search';
import VoiceSearch from './voice-search';
import ResultCard from './result-card';
import OffersMap from './offers';
import JourneySearch,{Address} from '../journey-search';
import './style.css';
const icons=[Wrench,Car,Bike,Monitor,Flower2,PawPrint];
export default function SearchClient({page,id,card}:{page:string;id:string;card:(p:Product,s:Shop)=>ReactNode}){
 const [query,setQuery]=useState(id),[city,setCity]=useState('Казань'),[cityEdit,setCityEdit]=useState(false),[ready,setReady]=useState(false),[journey,setJourney]=useState(false),[near,setNear]=useState<{lat:number;lng:number}>(),[manual,setManual]=useState(false),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState<SearchResponse|null>(null),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('');
 const context=useRef<SearchContext|undefined>(undefined),[geoExplain,setGeoExplain]=useState(false);
 const controller=useRef<AbortController|null>(null),rev=useRef(0),geoRev=useRef(0);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem('ng_search_context')||'null');if(saved&&Date.now()-saved.at<1800000)context.current=saved.context;}catch{}let alive=true;void fetch('/api/discovery').then(r=>r.json()).then(raw=>{if(!alive)return;const b=raw as {city:string};let saved='';try{saved=localStorage.getItem('ng_city')||'';}catch{}setCity(saved||b.city||'Казань');}).catch(()=>{}).finally(()=>{if(alive)setReady(true);});return()=>{alive=false;controller.current?.abort();geoRev.current++;};},[]);
 async function run(q:string){controller.current?.abort();const c=new AbortController();controller.current=c;const version=++rev.current;setBusy(true);setData(null);setError('');try{const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/x-ndjson'},body:JSON.stringify({query:q,city,near,context:context.current}),signal:c.signal});if(!r.ok||!r.body)throw Error('Не удалось выполнить поиск. Попробуйте позже.');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';for(;;){const {done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines.filter(Boolean)){const result=JSON.parse(line) as SearchResponse&{error?:string};if(version!==rev.current)return;if(result.error)setError(result.error);else {context.current=result.context;try{sessionStorage.setItem('ng_search_context',JSON.stringify({context:result.context,at:Date.now()}));}catch{}setData(result);}}if(done)break;}}catch(e){if(!c.signal.aborted)setError((e as Error).message);}finally{if(version===rev.current)setBusy(false);}}
 useEffect(()=>{if(!ready)return;setQuery(id);if(parseIntent(id,city).journey)setJourney(true);else if(page!=='home')void run(id);return()=>controller.current?.abort();},[page,id,city,near,ready]);
 function submit(q:string){const resolved=resolveSearch(q,context.current);setQuery(q);setFilter('all');if(parseIntent(resolved.query,city).journey){setJourney(true);setQuery(resolved.query);}const target='search/'+encodeURIComponent(q);if(location.hash.slice(1)===target)void run(q);else location.hash=target;}
 function locate(){if(!navigator.geolocation){setManual(true);return;}setNote('Определяем местоположение…');const n=++geoRev.current;navigator.geolocation.getCurrentPosition(p=>{if(n!==geoRev.current)return;setNear({lat:p.coords.latitude,lng:p.coords.longitude});setNote('Расстояния по прямой. Маршрут рассчитывается отдельно.');if(page==='home')submit(query);},()=>{if(n!==geoRev.current)return;setNote('Геолокация недоступна. Укажите адрес или район.');setManual(true);},{timeout:10000,maximumAge:60000});}
 const hits=(data?.hits||[]).filter(h=>filter==='all'||h.kind===filter),stores=hits.filter(h=>h.point&&h.address).map(hitShop);
 return <div className="finder"><div className="finder-location"><button onClick={()=>setCityEdit(!cityEdit)}><MapPin size={17}/>{city} · изменить</button></div>{cityEdit&&<form className="finder-city-form" onSubmit={e=>{e.preventDefault();const value=String(new FormData(e.currentTarget).get('city')).trim();if(!value)return;setCity(value);context.current=undefined;try{sessionStorage.removeItem('ng_search_context');}catch{}setNear(undefined);setCityEdit(false);try{localStorage.setItem('ng_city',value);}catch{}}}><label>Город<input name="city" defaultValue={city} maxLength={100} required/></label><button>Выбрать</button></form>}
 {page==='home'&&<div className="finder-opening"><p className="finder-kicker">ТОВАРЫ · УСЛУГИ · МАГАЗИНЫ</p><h1>Что хотите найти?</h1><p>Находите нужное в своём городе</p></div>}
 <VoiceSearch value={query} onChange={setQuery} busy={false} onSearch={()=>submit(query)}/><PhotoSearch onQuery={q=>{context.current=undefined;submit(q);}}/><div className="finder-modes"><button aria-pressed={!journey} onClick={()=>{setJourney(false);if(near)setNote('Используем указанное местоположение.');else setGeoExplain(true);}}>Рядом со мной</button><button aria-pressed={journey} onClick={()=>setJourney(true)}>По дороге</button></div>
 {geoExplain&&<div className="finder-note"><p>Местоположение нужно для расстояний и поиска рядом. Можно вместо него указать адрес; обычный поиск доступен без геолокации.</p><button onClick={()=>{setGeoExplain(false);locate();}}>Разрешить определение</button><button onClick={()=>{setGeoExplain(false);setManual(true);}}>Ввести адрес</button></div>}{note&&<p className="finder-note" role="status">{note}</p>}{manual&&<Address label="Адрес или район" value={null} onChange={p=>{if(p){setNear(p);setManual(false);setNote('Ищем возле '+p.label);if(page==='home')submit(query);}}}/>}{error&&<p role="alert" className="finder-error">{error}</p>}
 {journey?<JourneySearch query={query} city={city} card={card} onNearby={()=>{setJourney(false);void run(query);}}/>:page==='home'?<section className="finder-categories"><h2>Популярные категории</h2><div>{categories.map((c,i)=>{const Icon=icons[i];return <button key={c} onClick={()=>submit(c)}><Icon size={34}/><b>{c}</b></button>;})}</div><p className="finder-note">Ищем в каталоге и открытых картах. Наличие конкретного товара уточняйте у продавца.</p></section>:<><div className="finder-results-toolbar"><div className="finder-tabs">{[['all','Все'],['product','Товары'],['store','Магазины'],['service','Услуги'],['page','Сайты']].map(([value,label])=><button aria-pressed={filter===value} key={value} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="finder-tabs"><a href={'#search/'+encodeURIComponent(query)}>Список</a><a href={'#map/'+encodeURIComponent(query)}>Карта</a></div></div>{busy&&<p role="status">{data?'Проверяем внешние источники…':'Ищем в индексе…'}</p>}
 {data?.context&&<p className="finder-note">Текущий поиск: {data.context.query}{data.context.maxPrice!==undefined?` · до ${data.context.maxPrice} ₽`:''}{data.context.sort==='price'?' · сначала дешевле':''}. Можно уточнить запрос в строке выше.</p>}{!!data?.intent.clarification.length&&<p className="finder-note">Что вы имеете в виду? {data.intent.clarification.map(q=><button key={q} onClick={()=>submit(q)}>{q}</button>)}</p>}
 {data?.intent.kind==='complex'&&<p className="finder-note">Для этой задачи можно составить список покупок. <a href={'#plan-new/'+encodeURIComponent(query)}>Уточнить состав покупки →</a></p>}
 <div className={'finder-results-grid '+(page==='map'?'map-view':'')}><div>{hits.filter(h=>data?.context.maxPrice===undefined||h.price!==null).map(h=><ResultCard key={h.id} hit={h} onMap={key=>{setSelected(key);location.hash='map/'+encodeURIComponent(query);}}/>)}{data?.context.maxPrice!==undefined&&hits.some(h=>h.price===null)&&<section><h2>Цена неизвестна — уточните у продавца</h2><p className="finder-note">Эти результаты не подтверждают соответствие бюджету.</p>{hits.filter(h=>h.price===null).map(h=><ResultCard key={h.id} hit={h} onMap={key=>{setSelected(key);location.hash='map/'+encodeURIComponent(query);}}/>)}</section>}{!busy&&!hits.length&&<div className="finder-empty"><Search size={32}/><h2>Пока ничего не найдено</h2><p>Уточните запрос или город. Не все организации есть в открытых источниках.</p></div>}</div><aside><OffersMap stores={stores} offers={[]} selectedId={selected}/></aside></div>{data?.warnings.map(w=><p className="finder-note" key={w}>{w}</p>)}{data&&<small>{data.hits.length} результатов · {(data.timing.totalMs/1000).toFixed(1)} с</small>}</>}
 <p className="finder-credit"><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL</a>. Источник подтверждает запись об организации, не наличие товара.</p></div>;
}
