'use client';
import {trackProductEvent} from '@/lib/product-events';
import {complexRequest} from '@/lib/discovery';
import {explicitCityCandidate} from '@/lib/location-context';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {ChevronDown,Search,MapPin} from 'lucide-react';
import {categories,type Product,type Shop} from '@/lib/model';
import {parseIntent,hitShop} from '@/lib/city-search';
import type {SearchResponse} from '@/lib/search-engine';
import {resolveSearch,type SearchContext} from '@/lib/search-context';
import {cleanCity,cityKey} from '@/lib/location';
import {rememberSearch,takeReplay} from '@/lib/personal';

import SearchWaiting from './search-waiting';

import PhotoSearch from './photo-search';
import VoiceSearch from './voice-search';
import ResultCard from './result-card';
import OffersMap from './offers';
import JourneySearch,{Address} from '../journey-search';
import './style.css';
import './city.css';
const categoryImages=['home-repair','auto','sport','electronics','garden','pets'];
const categoryNotes=['Инструменты и материалы','Всё для автомобиля','Велосипеды и экипировка','Техника и аксессуары','Для участка и растений','Для кошек и собак'];
function resultCacheKey(city:string,query:string){return `ng_search_result:${cityKey(city)}:${query.trim().toLocaleLowerCase('ru-RU')}`;}
function cachedResult(city:string,query:string){try{const saved=JSON.parse(localStorage.getItem(resultCacheKey(city,query))||'null') as {at:number;data:SearchResponse}|null;return saved&&Date.now()-saved.at<24*3600000?saved.data:null;}catch{return null;}}
function rememberResult(city:string,query:string,data:SearchResponse){try{localStorage.setItem(resultCacheKey(city,query),JSON.stringify({at:Date.now(),data}));}catch{/* private browsing or storage full */}}
export default function SearchClient({page,id,card}:{page:string;id:string;card:(p:Product,s:Shop)=>ReactNode}){
 const [query,setQuery]=useState(id),[city,setCity]=useState(''),[cityEdit,setCityEdit]=useState(false),[ready,setReady]=useState(false),[headerReady,setHeaderReady]=useState(false),[journey,setJourney]=useState(false),[near,setNear]=useState<{lat:number;lng:number}>(),[manual,setManual]=useState(false),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState<SearchResponse|null>(null),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('');
 const searchPage=page==='home'?'home':'results';
 const replaying=useRef(false);
 const [shown,setShown]=useState(20);const manualCity=useRef(false);
 useEffect(()=>setShown(20),[id,filter,city]);
 const context=useRef<SearchContext|undefined>(undefined),[geoExplain,setGeoExplain]=useState(false);
 const controller=useRef<AbortController|null>(null),rev=useRef(0),geoRev=useRef(0);
 const mapGeoPrompted=useRef(false);
 useEffect(()=>setHeaderReady(true),[]);
 useEffect(()=>{const replay=takeReplay();if(replay){replaying.current=true;context.current=replay.context;setFilter(replay.filter);}let alive=true;try{const saved=localStorage.getItem('ng_city');if(saved){manualCity.current=true;setCity(saved);}}catch{}void fetch('/api/discovery').then(r=>r.json()).then(raw=>{if(!alive||manualCity.current)return;const b=raw as {city:string|null};if(b.city){setCity(b.city);try{sessionStorage.setItem('ng_current_city',b.city);}catch{}}else setCityEdit(true);}).catch(()=>{if(alive&&!manualCity.current)setCityEdit(true);}).finally(()=>{if(alive)setReady(true);});return()=>{alive=false;controller.current?.abort();geoRev.current++;};},[]);
 function changeCity(value:string,manual=true){const next=cleanCity(value);if(next.length<2)return;if(manual){manualCity.current=true;try{localStorage.setItem('ng_city',next);}catch{}}controller.current?.abort();rev.current++;geoRev.current++;setData(null);setSelected('');setBusy(false);context.current=undefined;try{sessionStorage.removeItem('ng_search_context');}catch{}setNear(undefined);setNote('');setManual(false);setCity(next);setError('');try{sessionStorage.setItem('ng_current_city',next);}catch{}setCityEdit(false);}
 async function geoCity(point:{lat:number;lng:number},version:number){try{const r=await fetch('/api/location',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(point)}),b=await r.json() as {city?:string;error?:string};if(version!==geoRev.current)return;if(!r.ok||!b.city)throw Error(b.error||'Не удалось определить город.');if(manualCity.current&&city.toLowerCase()!==b.city.toLowerCase()){setNote('Местоположение находится в другом городе. Сохраняем ваш выбор: '+city);return;}if(!manualCity.current)changeCity(b.city,false);setNear(point);setNote('Город: '+b.city+'. Расстояния по прямой; маршрут рассчитывается отдельно.');}catch(e){if(version===geoRev.current){setNote((e as Error).message);setManual(true);}}}

 async function run(q:string){if(!city){setCityEdit(true);setError('Укажите город для поиска.');return;}controller.current?.abort();const c=new AbortController();controller.current=c;const version=++rev.current;const deadline=window.setTimeout(()=>{if(version===rev.current){setError('Поиск занял слишком много времени. Повторите запрос позже.');c.abort();}},60000);setBusy(true);const saved=cachedResult(city,q);if(saved)setData(saved);else setData(current=>current&&current.context.query.trim().toLocaleLowerCase('ru-RU')===q.trim().toLocaleLowerCase('ru-RU')?current:null);setError('');const resume=replaying.current;replaying.current=false;try{const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/x-ndjson'},body:JSON.stringify({query:q,city,near,context:context.current,resume}),signal:c.signal});if(!r.ok){const b=await r.json().catch(()=>({})) as {error?:string};throw Error(b.error||'Не удалось выполнить поиск. Попробуйте позже.');}if(!r.body)throw Error('Не удалось выполнить поиск.');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';for(;;){const {done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines.filter(Boolean)){const result=JSON.parse(line) as SearchResponse&{error?:string};if(version!==rev.current)return;if(result.error)setError(result.error);else {context.current=result.context;try{sessionStorage.setItem('ng_search_context',JSON.stringify({city,context:result.context,at:Date.now()}));}catch{}setData(result);rememberResult(city,q,result);if(result.phase==='complete'){try{rememberSearch({query:q,city,filter,context:result.context});}catch(e){setNote((e as Error).message);}}if(result.phase==='complete'&&result.intent.journey){setQuery(result.context.query);setJourney(true);}}}if(done)break;}}catch(e){if(!c.signal.aborted)setError((e as Error).message);}finally{window.clearTimeout(deadline);if(version===rev.current)setBusy(false);}}
 useEffect(()=>{if(!city)return;try{const saved=JSON.parse(sessionStorage.getItem('ng_search_context')||'null');if(saved&&cityKey(saved.city||'')===cityKey(city)&&Date.now()-saved.at<30*60*1000&&typeof saved.context?.query==='string')context.current=saved.context;}catch{}},[city]);
 useEffect(()=>{if(page!=='home')return;controller.current?.abort();rev.current++;setBusy(false);setData(null);setQuery('');setFilter('all');setSelected('');setJourney(false);context.current=undefined;try{sessionStorage.removeItem('ng_search_context');}catch{}},[page]);
 useEffect(()=>{if(page==='map'&&ready&&!near&&!mapGeoPrompted.current){mapGeoPrompted.current=true;setGeoExplain(true);}},[page,ready,near]);
 useEffect(()=>{document.querySelector<HTMLElement>('.d-main')?.scrollTo({top:0,behavior:'auto'});},[page,id]);
 // Late city detection must not erase text already entered on the home screen.
 useEffect(()=>{if(!ready||!city||searchPage==='home')return;const resolved=resolveSearch(id,context.current);setQuery(id);if(parseIntent(resolved.query,city).journey){setQuery(resolved.query);setJourney(true);}else{if((parseIntent(id,city).nearby||/ближе/iu.test(id))&&!near)setGeoExplain(true);void run(id);}return()=>controller.current?.abort();},[searchPage,id,city,near,ready]);
 function begin(q:string){const resolved=resolveSearch(q,context.current);setQuery(q);setFilter('all');if(parseIntent(resolved.query,city).journey){setJourney(true);setQuery(resolved.query);}const target='search/'+encodeURIComponent(q);if(location.hash.slice(1)===target)void run(q);else location.hash=target;}
 async function submit(q:string){let text=q.trim();if(!text)return;if(explicitCityCandidate(text)){try{const r=await fetch('/api/location/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:text})});const b=await r.json() as {location?:{city:string;query:string}};if(b.location){changeCity(b.location.city);text=b.location.query;setQuery(text);location.hash='search/'+encodeURIComponent(text);return;}setNote('Город из запроса не подтверждён. Выберите его вручную.');setCityEdit(true);return;}catch{setNote('Выберите город вручную.');return;}}if(!city){setCityEdit(true);setError('Выберите город в верхней панели.');return;}begin(text);}
 function locate(){if(!navigator.geolocation){setManual(true);return;}setNote('Определяем местоположение…');const n=++geoRev.current;navigator.geolocation.getCurrentPosition(p=>{if(n!==geoRev.current)return;void geoCity({lat:p.coords.latitude,lng:p.coords.longitude},n);},()=>{if(n!==geoRev.current)return;setNote('Геолокация недоступна. Укажите адрес или район.');setManual(true);},{timeout:10000,maximumAge:60000});}
 const hits=(data?.hits||[]).filter(h=>filter==='page'?h.kind==='page':filter==='product'?h.kind==='product':filter==='all'?h.kind!=='page'&&h.locationEvidence!=='unverified':h.kind===filter&&h.locationEvidence!=='unverified'),visibleHits=hits.slice(0,shown),stores=hits.filter(h=>h.point&&h.address&&(h.locationEvidence==='confirmed-point'||h.shop?.addressConfirmed)).map(hitShop);
 const searchBox=<VoiceSearch value={query} onChange={setQuery} busy={false} onSearch={text=>submit(text??query)}/>;
 const searchExtras=<div className="finder-search-extras"><PhotoSearch onQuery={q=>{context.current=undefined;submit(q);}}/><button type="button" className="finder-nearby-action" onClick={()=>setGeoExplain(true)}><span className="finder-extra-icon nearby"><MapPin size={22}/></span><span><b>{near?'Местоположение учтено':'Уточнить, что рядом'}</b><small>{near?'Ищем с учётом вашей точки':'Например: «по дороге домой»'}</small></span></button></div>;
 const cityButton=<button type="button" className="finder-header-city" aria-label={`Текущий город: ${city||'не выбран'}. Изменить город`} onClick={()=>setCityEdit(true)}><MapPin size={17}/><span>{city||'Выбрать город'}</span><ChevronDown size={15}/></button>;
 const citySlot=headerReady?document.getElementById('buyer-city-slot'):null;
 return <div className={'finder finder-page-'+page}>{citySlot&&createPortal(cityButton,citySlot)}{cityEdit&&<form className="finder-city-form" onSubmit={e=>{e.preventDefault();const value=String(new FormData(e.currentTarget).get('city')).trim();if(!value)return;changeCity(value);}}><label>Выберите город<input name="city" defaultValue={city} minLength={2} maxLength={100} required autoFocus/></label><button className="finder-primary">Сохранить</button><button type="button" onClick={()=>{setGeoExplain(true);setCityEdit(false);}}>Определить автоматически</button><button type="button" aria-label="Закрыть выбор города" onClick={()=>setCityEdit(false)}>Закрыть</button></form>}
 {page==='home'?<section className="finder-home-hero"><div className="finder-opening"><p className="finder-kicker">ТОВАРЫ И УСЛУГИ РЯДОМ</p><h1>Что хотите найти?</h1><p>Опишите товар или задачу обычными словами — найдём предложения, продавцов и точки на карте.</p></div>{searchBox}{searchExtras}</section>:<>{searchBox}{searchExtras}</>}
 {geoExplain&&<div className="finder-note finder-location-note"><p>Местоположение нужно для расстояний и поиска рядом. Можно вместо него указать адрес; обычный поиск доступен без геолокации.</p><button onClick={()=>{setGeoExplain(false);locate();}}>Разрешить определение</button><button onClick={()=>{setGeoExplain(false);setManual(true);}}>Ввести адрес</button></div>}{note&&<p className="finder-note" role="status">{note}</p>}{manual&&<Address city={city} label="Адрес или район" value={null} onChange={p=>{if(p){setNear(p);setManual(false);setNote('Ищем возле '+p.label);if(page==='home')submit(query);}}}/>}{error&&<p role="alert" className="finder-error">{error} <a href="/account">Аккаунт и тариф</a></p>}
 {complexRequest(data?.context.query||query)&&!journey&&<div className="finder-note"><p>В запросе несколько покупок. Можно собрать отдельную подборку, не меняя обычный поиск.</p><button onClick={()=>{sessionStorage.setItem('ng_plan_task',data?.context.query||query);location.hash='plan-new';}}>Собрать список покупок</button></div>}{journey?<JourneySearch key={city} query={query} city={city} near={near} card={card} onNearby={()=>{setJourney(false);void run(query);}}/>:page==='home'?<section className="finder-categories"><div className="finder-section-heading"><div><p>БЫСТРЫЙ СТАРТ</p><h2>Что ищем сегодня?</h2></div><span>6 основных направлений</span></div><div>{categories.map((c,i)=><a className="finder-category-link" href={'#search/'+encodeURIComponent(c)} key={c} onClick={event=>{event.preventDefault();void submit(c);}}><img src={`/categories/${categoryImages[i]}.png`} alt=""/><span><b>{c}</b><small>{categoryNotes[i]}</small></span></a>)}</div><p className="finder-data-note">Ищем конкретные предложения и подходящие организации в выбранном городе. Цена и наличие показываются только когда их подтверждает источник.</p></section>:<><div className="finder-results-toolbar"><button disabled={!data||busy} onClick={()=>{try{rememberSearch({query:data!.context.query,city,filter,context:data!.context},true);trackProductEvent('saved_search',city);setNote('Поиск сохранён в разделе «Моё». При открытии предложения обновятся.');}catch(e){setNote((e as Error).message);}}}>Сохранить поиск</button><div className="finder-tabs">{[['all','Все'],['product','Товары'],['store','Магазины'],['service','Услуги'],['page','Сайты']].map(([value,label])=><button aria-pressed={filter===value} key={value} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="finder-tabs"><a href={'#search/'+encodeURIComponent(query)}>Список</a><a href={'#map/'+encodeURIComponent(query)}>Карта</a></div></div>{busy&&<SearchWaiting localReady={!!data}/>} 
 {data?.context&&<p className="finder-note finder-context-note">Текущий поиск: {data.context.query}{data.context.maxPrice!==undefined?` · до ${data.context.maxPrice} ₽`:''}{data.context.sort==='price-distance'?' · дешевле, затем ближе':data.context.sort==='price'?' · сначала дешевле':''}. Можно уточнить запрос в строке выше.</p>}{!!data?.intent.clarification.length&&<p className="finder-note">Что вы имеете в виду? {data.intent.clarification.map(q=><button key={q} onClick={()=>submit(q)}>{q}</button>)}</p>}
 {(data?.intent.kind==='complex'||(data?.context.query||query).split(/[,;\n]+/).filter(Boolean).length>1)&&<p className="finder-note">Для этой задачи можно составить список покупок. <a href={'#plan-new/'+encodeURIComponent(data?.context.query||query)}>Уточнить состав покупки →</a></p>}
 <div className={'finder-results-grid '+(page==='map'?'map-view':'')}><div>{visibleHits.filter(h=>data?.context.maxPrice===undefined||h.price!==null).map(h=><ResultCard key={h.id} hit={h} onMap={key=>{setSelected(key);location.hash='map/'+encodeURIComponent(query);}}/>)}{data?.context.maxPrice!==undefined&&hits.some(h=>h.price===null)&&<section><h2>Цена неизвестна — уточните у продавца</h2><p className="finder-note">Эти результаты не подтверждают соответствие бюджету.</p>{visibleHits.filter(h=>h.price===null).map(h=><ResultCard key={h.id} hit={h} onMap={key=>{setSelected(key);location.hash='map/'+encodeURIComponent(query);}}/>)}</section>}{hits.length>shown&&<button className="finder-primary" onClick={()=>setShown(n=>n+20)}>Показать ещё · осталось {hits.length-shown}</button>}{!busy&&!hits.length&&<div className="finder-empty"><Search size={32}/><h2>Пока ничего не найдено</h2><p>Уточните запрос или город. Не все организации есть в открытых источниках.</p></div>}</div><aside><OffersMap stores={stores} offers={[]} selectedId={selected} near={near} onRequestLocation={()=>setGeoExplain(true)}/></aside></div>{data?.warnings.map(w=><p className="finder-note" key={w}>{w}</p>)}{data&&<small>{data.hits.length} результатов · {(data.timing.totalMs/1000).toFixed(1)} с</small>}</>}
 <p className="finder-credit"><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL</a>. Источник подтверждает запись об организации, не наличие товара.</p></div>;
}
